using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public sealed partial class RangeTemplates : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4898656118771152014UL,7349591471542998915UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public Ranges Ranges
	{
		get => (Ranges) _Ranges[Index];
		set => _Ranges[Index] = value;
	}
	public Core.Generated.ValueEnum ValueEnum => (Core.Generated.ValueEnum) _ValueEnum.GetStoredValue(Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5099729241591029650UL, 4701470807071251364UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_Ranges;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _Ranges => _ufle12jhs77_Ranges ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5402904970816027210UL, 17749564478748189095UL), () => _ufle12jhs77_Ranges = null);
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_ValueEnum;
	public static BansheeGz.BGDatabase.BGFieldEnum _ValueEnum => _ufle12jhs77_ValueEnum ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(4815465141202628665UL, 15792224234827158959UL), () => _ufle12jhs77_ValueEnum = null);
	public List<ValueSets> RelatedValueSetsListUsingValuesRelation => BGCodeGenUtils.GetRelatedInbound<ValueSets>(ValueSets._Values, Id);
	private RangeTemplates() : base(MetaDefault) {}
	private RangeTemplates(BGId id) : base(MetaDefault, id) {}
	private RangeTemplates(BGMetaEntity meta) : base(meta) {}
	private RangeTemplates(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static RangeTemplates FindEntity(Predicate<RangeTemplates> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<RangeTemplates> FindEntities(Predicate<RangeTemplates> filter, List<RangeTemplates> result=null, Comparison<RangeTemplates> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<RangeTemplates> action, Predicate<RangeTemplates> filter=null, Comparison<RangeTemplates> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static RangeTemplates GetEntity(BGId entityId) => (RangeTemplates) MetaDefault.GetEntity(entityId);
	public static RangeTemplates GetEntity(int index) => (RangeTemplates) MetaDefault[index];
	public static RangeTemplates GetEntity(string entityName) => (RangeTemplates) MetaDefault.GetEntity(entityName);
	public static RangeTemplates NewEntity() => (RangeTemplates) MetaDefault.NewEntity();
	public static RangeTemplates NewEntity(BGId entityId) => (RangeTemplates) MetaDefault.NewEntity(entityId);
	public static RangeTemplates NewEntity(Action<RangeTemplates> callback) => (RangeTemplates) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((RangeTemplates)entity)));
	public List<ValueSets> FillRelatedValueSetsListUsingValuesRelation(List<ValueSets> result) => BGCodeGenUtils.GetRelatedInbound<ValueSets>(ValueSets._Values, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4898656118771152014UL,7349591471542998915UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5099729241591029650UL, 4701470807071251364UL));
		_ufle12jhs77_Ranges = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5402904970816027210UL, 17749564478748189095UL));
		_ufle12jhs77_ValueEnum = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(_metaDefault, new BGId(4815465141202628665UL, 15792224234827158959UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Ranges = null;
		_ufle12jhs77_ValueEnum = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new RangeTemplates(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new RangeTemplates(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "RangeTemplates";
		public const string name = "name";
		public const string Ranges = "Ranges";
		public const string ValueEnum = "ValueEnum";
	}
}

[Preserve]
public sealed partial class ValueSets : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5716822476408136107UL,12097655307414520729UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public List<RangeTemplates> Values => BGCodeGenUtils.MultipleRelationGet<RangeTemplates>(_Values, Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5377879880523520194UL, 5923750984130547072UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_Values;
	public static BansheeGz.BGDatabase.BGFieldRelationMultiple _Values => _ufle12jhs77_Values ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(5604254516071536533UL, 14870553348063887292UL), () => _ufle12jhs77_Values = null);
	private ValueSets() : base(MetaDefault) {}
	private ValueSets(BGId id) : base(MetaDefault, id) {}
	private ValueSets(BGMetaEntity meta) : base(meta) {}
	private ValueSets(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static ValueSets FindEntity(Predicate<ValueSets> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<ValueSets> FindEntities(Predicate<ValueSets> filter, List<ValueSets> result=null, Comparison<ValueSets> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<ValueSets> action, Predicate<ValueSets> filter=null, Comparison<ValueSets> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static ValueSets GetEntity(BGId entityId) => (ValueSets) MetaDefault.GetEntity(entityId);
	public static ValueSets GetEntity(int index) => (ValueSets) MetaDefault[index];
	public static ValueSets GetEntity(string entityName) => (ValueSets) MetaDefault.GetEntity(entityName);
	public static ValueSets NewEntity() => (ValueSets) MetaDefault.NewEntity();
	public static ValueSets NewEntity(BGId entityId) => (ValueSets) MetaDefault.NewEntity(entityId);
	public static ValueSets NewEntity(Action<ValueSets> callback) => (ValueSets) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((ValueSets)entity)));
	public void Values_Add(RangeTemplates related) => BGCodeGenUtils.MultipleRelationAdd(_Values, Index, related);
	public void Values_Remove(RangeTemplates related) => BGCodeGenUtils.MultipleRelationRemove(_Values, Index, related);
	public List<RangeTemplates> FillValues(List<RangeTemplates> result) => BGCodeGenUtils.MultipleRelationGet<RangeTemplates>(_Values, Index, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5716822476408136107UL,12097655307414520729UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5377879880523520194UL, 5923750984130547072UL));
		_ufle12jhs77_Values = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(_metaDefault, new BGId(5604254516071536533UL, 14870553348063887292UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Values = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new ValueSets(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new ValueSets(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "ValueSets";
		public const string name = "name";
		public const string Values = "Values";
	}
}

[Preserve]
public sealed partial class PropgressionCurves : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5441332370735314639UL,4125961409994376623UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public UnityEngine.AnimationCurve Curve => _Curve[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5639873407202193959UL, 10007965060530124727UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldAnimationCurve2020 _ufle12jhs77_Curve;
	public static BansheeGz.BGDatabase.BGFieldAnimationCurve2020 _Curve => _ufle12jhs77_Curve ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldAnimationCurve2020>(MetaDefault, new BGId(5619372236412538168UL, 2346073379865126822UL), () => _ufle12jhs77_Curve = null);
	public List<Ranges> RelatedRangesListUsingProgressionCurveLowRelation => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._ProgressionCurveLow, Id);
	public List<Ranges> RelatedRangesListUsingProgressionCurveHighRelation => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._ProgressionCurveHigh, Id);
	public List<Ranges> RelatedRangesListUsingCorrectionCurveRelation => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._CorrectionCurve, Id);
	private PropgressionCurves() : base(MetaDefault) {}
	private PropgressionCurves(BGId id) : base(MetaDefault, id) {}
	private PropgressionCurves(BGMetaEntity meta) : base(meta) {}
	private PropgressionCurves(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static PropgressionCurves FindEntity(Predicate<PropgressionCurves> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<PropgressionCurves> FindEntities(Predicate<PropgressionCurves> filter, List<PropgressionCurves> result=null, Comparison<PropgressionCurves> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<PropgressionCurves> action, Predicate<PropgressionCurves> filter=null, Comparison<PropgressionCurves> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static PropgressionCurves GetEntity(BGId entityId) => (PropgressionCurves) MetaDefault.GetEntity(entityId);
	public static PropgressionCurves GetEntity(int index) => (PropgressionCurves) MetaDefault[index];
	public static PropgressionCurves GetEntity(string entityName) => (PropgressionCurves) MetaDefault.GetEntity(entityName);
	public static PropgressionCurves NewEntity() => (PropgressionCurves) MetaDefault.NewEntity();
	public static PropgressionCurves NewEntity(BGId entityId) => (PropgressionCurves) MetaDefault.NewEntity(entityId);
	public static PropgressionCurves NewEntity(Action<PropgressionCurves> callback) => (PropgressionCurves) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((PropgressionCurves)entity)));
	public List<Ranges> FillRelatedRangesListUsingProgressionCurveLowRelation(List<Ranges> result) => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._ProgressionCurveLow, Id, result);
	public List<Ranges> FillRelatedRangesListUsingProgressionCurveHighRelation(List<Ranges> result) => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._ProgressionCurveHigh, Id, result);
	public List<Ranges> FillRelatedRangesListUsingCorrectionCurveRelation(List<Ranges> result) => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._CorrectionCurve, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5441332370735314639UL,4125961409994376623UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5639873407202193959UL, 10007965060530124727UL));
		_ufle12jhs77_Curve = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldAnimationCurve2020>(_metaDefault, new BGId(5619372236412538168UL, 2346073379865126822UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Curve = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new PropgressionCurves(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new PropgressionCurves(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "PropgressionCurves";
		public const string name = "name";
		public const string Curve = "Curve";
	}
}

[Preserve]
public sealed partial class Ranges : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4635767876034809878UL,4045935601704716205UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String View => _View[Index];
	public System.Single LowMin
	{
		get => _LowMin[Index];
		set => _LowMin.SetValue(this, value);
	}
	public System.Single HighMin
	{
		get => _HighMin[Index];
		set => _HighMin.SetValue(this, value);
	}
	public System.Single LowMax => _LowMax[Index];
	public System.Single HighMax => _HighMax[Index];
	public ValueStandarts ValueStandart => (ValueStandarts) _ValueStandart[Index];
	public PropgressionCurves ProgressionCurveLow => (PropgressionCurves) _ProgressionCurveLow[Index];
	public PropgressionCurves ProgressionCurveHigh
	{
		get => (PropgressionCurves) _ProgressionCurveHigh[Index];
		set => _ProgressionCurveHigh[Index] = value;
	}
	public PropgressionCurves CorrectionCurve => (PropgressionCurves) _CorrectionCurve[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5049529740296329327UL, 10832680592029824902UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldCalcString _ufle12jhs77_View;
	public static BansheeGz.BGDatabase.BGFieldCalcString _View => _ufle12jhs77_View ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldCalcString>(MetaDefault, new BGId(4820686030070571126UL, 16061798305095414954UL), () => _ufle12jhs77_View = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_LowMin;
	public static BansheeGz.BGDatabase.BGFieldFloat _LowMin => _ufle12jhs77_LowMin ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5614260526340195007UL, 4534296045324915638UL), () => _ufle12jhs77_LowMin = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_HighMin;
	public static BansheeGz.BGDatabase.BGFieldFloat _HighMin => _ufle12jhs77_HighMin ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5549375653461143862UL, 7230639287146469532UL), () => _ufle12jhs77_HighMin = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_LowMax;
	public static BansheeGz.BGDatabase.BGFieldFloat _LowMax => _ufle12jhs77_LowMax ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4749131031964540908UL, 12202097326895461002UL), () => _ufle12jhs77_LowMax = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_HighMax;
	public static BansheeGz.BGDatabase.BGFieldFloat _HighMax => _ufle12jhs77_HighMax ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4970799708984032045UL, 8690622849447729823UL), () => _ufle12jhs77_HighMax = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_ValueStandart;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _ValueStandart => _ufle12jhs77_ValueStandart ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5576961620776170063UL, 7628888682198243981UL), () => _ufle12jhs77_ValueStandart = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_ProgressionCurveLow;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _ProgressionCurveLow => _ufle12jhs77_ProgressionCurveLow ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5116479149695975793UL, 10995971326024846739UL), () => _ufle12jhs77_ProgressionCurveLow = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_ProgressionCurveHigh;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _ProgressionCurveHigh => _ufle12jhs77_ProgressionCurveHigh ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5081730945958718802UL, 7315592511670007208UL), () => _ufle12jhs77_ProgressionCurveHigh = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_CorrectionCurve;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _CorrectionCurve => _ufle12jhs77_CorrectionCurve ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4706639196142366745UL, 12135456538631314874UL), () => _ufle12jhs77_CorrectionCurve = null);
	public List<RangeTemplates> RelatedRangeTemplatesListUsingRangesRelation => BGCodeGenUtils.GetRelatedInbound<RangeTemplates>(RangeTemplates._Ranges, Id);
	private Ranges() : base(MetaDefault) {}
	private Ranges(BGId id) : base(MetaDefault, id) {}
	private Ranges(BGMetaEntity meta) : base(meta) {}
	private Ranges(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static Ranges FindEntity(Predicate<Ranges> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<Ranges> FindEntities(Predicate<Ranges> filter, List<Ranges> result=null, Comparison<Ranges> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Ranges> action, Predicate<Ranges> filter=null, Comparison<Ranges> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static Ranges GetEntity(BGId entityId) => (Ranges) MetaDefault.GetEntity(entityId);
	public static Ranges GetEntity(int index) => (Ranges) MetaDefault[index];
	public static Ranges GetEntity(string entityName) => (Ranges) MetaDefault.GetEntity(entityName);
	public static Ranges NewEntity() => (Ranges) MetaDefault.NewEntity();
	public static Ranges NewEntity(BGId entityId) => (Ranges) MetaDefault.NewEntity(entityId);
	public static Ranges NewEntity(Action<Ranges> callback) => (Ranges) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Ranges)entity)));
	public List<RangeTemplates> FillRelatedRangeTemplatesListUsingRangesRelation(List<RangeTemplates> result) => BGCodeGenUtils.GetRelatedInbound<RangeTemplates>(RangeTemplates._Ranges, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4635767876034809878UL,4045935601704716205UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5049529740296329327UL, 10832680592029824902UL));
		_ufle12jhs77_View = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldCalcString>(_metaDefault, new BGId(4820686030070571126UL, 16061798305095414954UL));
		_ufle12jhs77_LowMin = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5614260526340195007UL, 4534296045324915638UL));
		_ufle12jhs77_HighMin = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5549375653461143862UL, 7230639287146469532UL));
		_ufle12jhs77_LowMax = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4749131031964540908UL, 12202097326895461002UL));
		_ufle12jhs77_HighMax = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4970799708984032045UL, 8690622849447729823UL));
		_ufle12jhs77_ValueStandart = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5576961620776170063UL, 7628888682198243981UL));
		_ufle12jhs77_ProgressionCurveLow = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5116479149695975793UL, 10995971326024846739UL));
		_ufle12jhs77_ProgressionCurveHigh = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5081730945958718802UL, 7315592511670007208UL));
		_ufle12jhs77_CorrectionCurve = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4706639196142366745UL, 12135456538631314874UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_View = null;
		_ufle12jhs77_LowMin = null;
		_ufle12jhs77_HighMin = null;
		_ufle12jhs77_LowMax = null;
		_ufle12jhs77_HighMax = null;
		_ufle12jhs77_ValueStandart = null;
		_ufle12jhs77_ProgressionCurveLow = null;
		_ufle12jhs77_ProgressionCurveHigh = null;
		_ufle12jhs77_CorrectionCurve = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Ranges(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Ranges(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Ranges";
		public const string name = "name";
		public const string View = "View";
		public const string LowMin = "LowMin";
		public const string HighMin = "HighMin";
		public const string LowMax = "LowMax";
		public const string HighMax = "HighMax";
		public const string ValueStandart = "ValueStandart";
		public const string ProgressionCurveLow = "ProgressionCurveLow";
		public const string ProgressionCurveHigh = "ProgressionCurveHigh";
		public const string CorrectionCurve = "CorrectionCurve";
	}
}

[Preserve]
public sealed partial class ValueStandarts : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5091801755773772909UL,4171289196249117874UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Single Value => _Value[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5164306217405180705UL, 15153739852246655370UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Value;
	public static BansheeGz.BGDatabase.BGFieldFloat _Value => _ufle12jhs77_Value ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5647768308188824185UL, 12844356746291314336UL), () => _ufle12jhs77_Value = null);
	public List<Ranges> RelatedRangesListUsingValueStandartRelation => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._ValueStandart, Id);
	private ValueStandarts() : base(MetaDefault) {}
	private ValueStandarts(BGId id) : base(MetaDefault, id) {}
	private ValueStandarts(BGMetaEntity meta) : base(meta) {}
	private ValueStandarts(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static ValueStandarts FindEntity(Predicate<ValueStandarts> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<ValueStandarts> FindEntities(Predicate<ValueStandarts> filter, List<ValueStandarts> result=null, Comparison<ValueStandarts> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<ValueStandarts> action, Predicate<ValueStandarts> filter=null, Comparison<ValueStandarts> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static ValueStandarts GetEntity(BGId entityId) => (ValueStandarts) MetaDefault.GetEntity(entityId);
	public static ValueStandarts GetEntity(int index) => (ValueStandarts) MetaDefault[index];
	public static ValueStandarts GetEntity(string entityName) => (ValueStandarts) MetaDefault.GetEntity(entityName);
	public static ValueStandarts NewEntity() => (ValueStandarts) MetaDefault.NewEntity();
	public static ValueStandarts NewEntity(BGId entityId) => (ValueStandarts) MetaDefault.NewEntity(entityId);
	public static ValueStandarts NewEntity(Action<ValueStandarts> callback) => (ValueStandarts) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((ValueStandarts)entity)));
	public List<Ranges> FillRelatedRangesListUsingValueStandartRelation(List<Ranges> result) => BGCodeGenUtils.GetRelatedInbound<Ranges>(Ranges._ValueStandart, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5091801755773772909UL,4171289196249117874UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5164306217405180705UL, 15153739852246655370UL));
		_ufle12jhs77_Value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5647768308188824185UL, 12844356746291314336UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Value = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new ValueStandarts(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new ValueStandarts(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "ValueStandarts";
		public const string name = "name";
		public const string Value = "Value";
	}
}

[Preserve]
public sealed partial class Quest_Kills : BGEntity, IQuests
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4634905807947090607UL,15170298109875658939UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.Int32 RequiredCount => _RequiredCount[Index];
	public UnityEngine.GameObject Prefab => _Prefab[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4780414324155020017UL, 6094819861608427678UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_RequiredCount;
	public static BansheeGz.BGDatabase.BGFieldInt _RequiredCount => _ufle12jhs77_RequiredCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4674580326030382130UL, 17899386973896031872UL), () => _ufle12jhs77_RequiredCount = null);
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_Prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _Prefab => _ufle12jhs77_Prefab ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(4796994424380784254UL, 8703982363425169303UL), () => _ufle12jhs77_Prefab = null);
	public List<Quests> RelatedQuestsListUsingLinkRelation => BGCodeGenUtils.GetRelatedInbound<Quests>(Quests._Link, Id);
	private Quest_Kills() : base(MetaDefault) {}
	private Quest_Kills(BGId id) : base(MetaDefault, id) {}
	private Quest_Kills(BGMetaEntity meta) : base(meta) {}
	private Quest_Kills(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static Quest_Kills FindEntity(Predicate<Quest_Kills> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<Quest_Kills> FindEntities(Predicate<Quest_Kills> filter, List<Quest_Kills> result=null, Comparison<Quest_Kills> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Quest_Kills> action, Predicate<Quest_Kills> filter=null, Comparison<Quest_Kills> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static Quest_Kills GetEntity(BGId entityId) => (Quest_Kills) MetaDefault.GetEntity(entityId);
	public static Quest_Kills GetEntity(int index) => (Quest_Kills) MetaDefault[index];
	public static Quest_Kills GetEntity(string entityName) => (Quest_Kills) MetaDefault.GetEntity(entityName);
	public static Quest_Kills NewEntity() => (Quest_Kills) MetaDefault.NewEntity();
	public static Quest_Kills NewEntity(BGId entityId) => (Quest_Kills) MetaDefault.NewEntity(entityId);
	public static Quest_Kills NewEntity(Action<Quest_Kills> callback) => (Quest_Kills) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Quest_Kills)entity)));
	public List<Quests> FillRelatedQuestsListUsingLinkRelation(List<Quests> result) => BGCodeGenUtils.GetRelatedInbound<Quests>(Quests._Link, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4634905807947090607UL,15170298109875658939UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4780414324155020017UL, 6094819861608427678UL));
		_ufle12jhs77_RequiredCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4674580326030382130UL, 17899386973896031872UL));
		_ufle12jhs77_Prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(_metaDefault, new BGId(4796994424380784254UL, 8703982363425169303UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_RequiredCount = null;
		_ufle12jhs77_Prefab = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Quest_Kills(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Quest_Kills(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Quest_Kills";
		public const string name = "name";
		public const string RequiredCount = "RequiredCount";
		public const string Prefab = "Prefab";
	}
}

[Preserve]
public sealed partial class Quests : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5121696395905606201UL,6315781243949073044UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public IQuests Link
	{
		get => (IQuests) _Link[Index];
		set => _Link[Index] = (BGEntity) value;
	}
	public List<IReward> Rewards => BGCodeGenUtils.MultipleViewRelationGet<IReward>(_Rewards, Index);
	public UnityEngine.GameObject OnCompleteTaskPrefab => _OnCompleteTaskPrefab[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5671834615099684038UL, 5598931718689838761UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldViewRelationSingle _ufle12jhs77_Link;
	public static BansheeGz.BGDatabase.BGFieldViewRelationSingle _Link => _ufle12jhs77_Link ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldViewRelationSingle>(MetaDefault, new BGId(5405925522058196731UL, 4494184002102053307UL), () => _ufle12jhs77_Link = null);
	private static BansheeGz.BGDatabase.BGFieldViewRelationMultiple _ufle12jhs77_Rewards;
	public static BansheeGz.BGDatabase.BGFieldViewRelationMultiple _Rewards => _ufle12jhs77_Rewards ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldViewRelationMultiple>(MetaDefault, new BGId(4681944044731535151UL, 7753402565612764841UL), () => _ufle12jhs77_Rewards = null);
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_OnCompleteTaskPrefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _OnCompleteTaskPrefab => _ufle12jhs77_OnCompleteTaskPrefab ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5577374860837369958UL, 9336104662398018718UL), () => _ufle12jhs77_OnCompleteTaskPrefab = null);
	private Quests() : base(MetaDefault) {}
	private Quests(BGId id) : base(MetaDefault, id) {}
	private Quests(BGMetaEntity meta) : base(meta) {}
	private Quests(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static Quests FindEntity(Predicate<Quests> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<Quests> FindEntities(Predicate<Quests> filter, List<Quests> result=null, Comparison<Quests> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Quests> action, Predicate<Quests> filter=null, Comparison<Quests> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static Quests GetEntity(BGId entityId) => (Quests) MetaDefault.GetEntity(entityId);
	public static Quests GetEntity(int index) => (Quests) MetaDefault[index];
	public static Quests GetEntity(string entityName) => (Quests) MetaDefault.GetEntity(entityName);
	public static Quests NewEntity() => (Quests) MetaDefault.NewEntity();
	public static Quests NewEntity(BGId entityId) => (Quests) MetaDefault.NewEntity(entityId);
	public static Quests NewEntity(Action<Quests> callback) => (Quests) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Quests)entity)));
	public List<IReward> FillRewards(List<IReward> result) => BGCodeGenUtils.MultipleRelationGet<IReward>(_Rewards, Index, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5121696395905606201UL,6315781243949073044UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5671834615099684038UL, 5598931718689838761UL));
		_ufle12jhs77_Link = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldViewRelationSingle>(_metaDefault, new BGId(5405925522058196731UL, 4494184002102053307UL));
		_ufle12jhs77_Rewards = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldViewRelationMultiple>(_metaDefault, new BGId(4681944044731535151UL, 7753402565612764841UL));
		_ufle12jhs77_OnCompleteTaskPrefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(_metaDefault, new BGId(5577374860837369958UL, 9336104662398018718UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Link = null;
		_ufle12jhs77_Rewards = null;
		_ufle12jhs77_OnCompleteTaskPrefab = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Quests(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Quests(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Quests";
		public const string name = "name";
		public const string Link = "Link";
		public const string Rewards = "Rewards";
		public const string OnCompleteTaskPrefab = "OnCompleteTaskPrefab";
	}
}

[Preserve]
public sealed partial class RewardGold : BGEntity, IReward
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5588342634143607386UL,7208147853559112364UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public UnityEngine.Sprite Icon => _Icon[Index];
	public System.Int32 Count
	{
		get => _Count[Index];
		set => _Count.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5297136571792443078UL, 12531343253636560287UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_Icon;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _Icon => _ufle12jhs77_Icon ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5257043224476839524UL, 5492754694273662614UL), () => _ufle12jhs77_Icon = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Count;
	public static BansheeGz.BGDatabase.BGFieldInt _Count => _ufle12jhs77_Count ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5616391670774387076UL, 17234946300436819620UL), () => _ufle12jhs77_Count = null);
	public List<Quests> RelatedQuestsListUsingRewardsRelation => BGCodeGenUtils.GetRelatedInbound<Quests>(Quests._Rewards, Id);
	private RewardGold() : base(MetaDefault) {}
	private RewardGold(BGId id) : base(MetaDefault, id) {}
	private RewardGold(BGMetaEntity meta) : base(meta) {}
	private RewardGold(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static RewardGold FindEntity(Predicate<RewardGold> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<RewardGold> FindEntities(Predicate<RewardGold> filter, List<RewardGold> result=null, Comparison<RewardGold> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<RewardGold> action, Predicate<RewardGold> filter=null, Comparison<RewardGold> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static RewardGold GetEntity(BGId entityId) => (RewardGold) MetaDefault.GetEntity(entityId);
	public static RewardGold GetEntity(int index) => (RewardGold) MetaDefault[index];
	public static RewardGold GetEntity(string entityName) => (RewardGold) MetaDefault.GetEntity(entityName);
	public static RewardGold NewEntity() => (RewardGold) MetaDefault.NewEntity();
	public static RewardGold NewEntity(BGId entityId) => (RewardGold) MetaDefault.NewEntity(entityId);
	public static RewardGold NewEntity(Action<RewardGold> callback) => (RewardGold) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((RewardGold)entity)));
	public List<Quests> FillRelatedQuestsListUsingRewardsRelation(List<Quests> result) => BGCodeGenUtils.GetRelatedInbound<Quests>(Quests._Rewards, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5588342634143607386UL,7208147853559112364UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5297136571792443078UL, 12531343253636560287UL));
		_ufle12jhs77_Icon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(_metaDefault, new BGId(5257043224476839524UL, 5492754694273662614UL));
		_ufle12jhs77_Count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5616391670774387076UL, 17234946300436819620UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Icon = null;
		_ufle12jhs77_Count = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new RewardGold(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new RewardGold(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "RewardGold";
		public const string name = "name";
		public const string Icon = "Icon";
		public const string Count = "Count";
	}
}

[Preserve]
public sealed partial class Entrances : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5053962645146764437UL,7095354471628614050UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public Locations Location
	{
		get => (Locations) _Location[Index];
		set => _Location[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5372194869076978533UL, 16979153404115850922UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_Location;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _Location => _ufle12jhs77_Location ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5730384710383748292UL, 12469998765259904149UL), () => _ufle12jhs77_Location = null);
	public List<EntranceRelations> RelatedEntranceRelationsListUsingFromRelation => BGCodeGenUtils.GetRelatedInbound<EntranceRelations>(EntranceRelations._From, Id);
	public List<EntranceRelations> RelatedEntranceRelationsListUsingToRelation => BGCodeGenUtils.GetRelatedInbound<EntranceRelations>(EntranceRelations._To, Id);
	private Entrances() : base(MetaDefault) {}
	private Entrances(BGId id) : base(MetaDefault, id) {}
	private Entrances(BGMetaEntity meta) : base(meta) {}
	private Entrances(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static Entrances FindEntity(Predicate<Entrances> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<Entrances> FindEntities(Predicate<Entrances> filter, List<Entrances> result=null, Comparison<Entrances> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Entrances> action, Predicate<Entrances> filter=null, Comparison<Entrances> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static Entrances GetEntity(BGId entityId) => (Entrances) MetaDefault.GetEntity(entityId);
	public static Entrances GetEntity(int index) => (Entrances) MetaDefault[index];
	public static Entrances GetEntity(string entityName) => (Entrances) MetaDefault.GetEntity(entityName);
	public static Entrances NewEntity() => (Entrances) MetaDefault.NewEntity();
	public static Entrances NewEntity(BGId entityId) => (Entrances) MetaDefault.NewEntity(entityId);
	public static Entrances NewEntity(Action<Entrances> callback) => (Entrances) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Entrances)entity)));
	public List<EntranceRelations> FillRelatedEntranceRelationsListUsingFromRelation(List<EntranceRelations> result) => BGCodeGenUtils.GetRelatedInbound<EntranceRelations>(EntranceRelations._From, Id, result);
	public List<EntranceRelations> FillRelatedEntranceRelationsListUsingToRelation(List<EntranceRelations> result) => BGCodeGenUtils.GetRelatedInbound<EntranceRelations>(EntranceRelations._To, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5053962645146764437UL,7095354471628614050UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5372194869076978533UL, 16979153404115850922UL));
		_ufle12jhs77_Location = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5730384710383748292UL, 12469998765259904149UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Location = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Entrances(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Entrances(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Entrances";
		public const string name = "name";
		public const string Location = "Location";
	}
}

[Preserve]
public sealed partial class EntranceRelations : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5665937695245311341UL,14166996636501286334UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public Entrances From => (Entrances) _From[Index];
	public Entrances To => (Entrances) _To[Index];
	public System.Boolean IsBidirectional => _IsBidirectional[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5426917963777398212UL, 17038345019527527319UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_From;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _From => _ufle12jhs77_From ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4934609369487349243UL, 8658245101147785390UL), () => _ufle12jhs77_From = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_To;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _To => _ufle12jhs77_To ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5379722181386872057UL, 4318530751568627843UL), () => _ufle12jhs77_To = null);
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_IsBidirectional;
	public static BansheeGz.BGDatabase.BGFieldBool _IsBidirectional => _ufle12jhs77_IsBidirectional ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5470423573830877132UL, 12379935407369743791UL), () => _ufle12jhs77_IsBidirectional = null);
	private EntranceRelations() : base(MetaDefault) {}
	private EntranceRelations(BGId id) : base(MetaDefault, id) {}
	private EntranceRelations(BGMetaEntity meta) : base(meta) {}
	private EntranceRelations(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static EntranceRelations FindEntity(Predicate<EntranceRelations> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<EntranceRelations> FindEntities(Predicate<EntranceRelations> filter, List<EntranceRelations> result=null, Comparison<EntranceRelations> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<EntranceRelations> action, Predicate<EntranceRelations> filter=null, Comparison<EntranceRelations> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static EntranceRelations GetEntity(BGId entityId) => (EntranceRelations) MetaDefault.GetEntity(entityId);
	public static EntranceRelations GetEntity(int index) => (EntranceRelations) MetaDefault[index];
	public static EntranceRelations GetEntity(string entityName) => (EntranceRelations) MetaDefault.GetEntity(entityName);
	public static EntranceRelations NewEntity() => (EntranceRelations) MetaDefault.NewEntity();
	public static EntranceRelations NewEntity(BGId entityId) => (EntranceRelations) MetaDefault.NewEntity(entityId);
	public static EntranceRelations NewEntity(Action<EntranceRelations> callback) => (EntranceRelations) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((EntranceRelations)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5665937695245311341UL,14166996636501286334UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5426917963777398212UL, 17038345019527527319UL));
		_ufle12jhs77_From = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4934609369487349243UL, 8658245101147785390UL));
		_ufle12jhs77_To = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5379722181386872057UL, 4318530751568627843UL));
		_ufle12jhs77_IsBidirectional = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5470423573830877132UL, 12379935407369743791UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_From = null;
		_ufle12jhs77_To = null;
		_ufle12jhs77_IsBidirectional = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new EntranceRelations(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new EntranceRelations(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "EntranceRelations";
		public const string name = "name";
		public const string From = "From";
		public const string To = "To";
		public const string IsBidirectional = "IsBidirectional";
	}
}

[Preserve]
public sealed partial class Locations : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4813906483841145583UL,2916551055859798656UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5256612705798366190UL, 17805978858233026978UL), () => _ufle12jhs77_name = null);
	public List<Entrances> RelatedEntrancesListUsingLocationRelation => BGCodeGenUtils.GetRelatedInbound<Entrances>(Entrances._Location, Id);
	public List<Quest_Kill_all> RelatedQuest_Kill_allListUsingLocationRelation => BGCodeGenUtils.GetRelatedInbound<Quest_Kill_all>(Quest_Kill_all._Location, Id);
	private Locations() : base(MetaDefault) {}
	private Locations(BGId id) : base(MetaDefault, id) {}
	private Locations(BGMetaEntity meta) : base(meta) {}
	private Locations(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static Locations FindEntity(Predicate<Locations> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<Locations> FindEntities(Predicate<Locations> filter, List<Locations> result=null, Comparison<Locations> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Locations> action, Predicate<Locations> filter=null, Comparison<Locations> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static Locations GetEntity(BGId entityId) => (Locations) MetaDefault.GetEntity(entityId);
	public static Locations GetEntity(int index) => (Locations) MetaDefault[index];
	public static Locations GetEntity(string entityName) => (Locations) MetaDefault.GetEntity(entityName);
	public static Locations NewEntity() => (Locations) MetaDefault.NewEntity();
	public static Locations NewEntity(BGId entityId) => (Locations) MetaDefault.NewEntity(entityId);
	public static Locations NewEntity(Action<Locations> callback) => (Locations) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Locations)entity)));
	public List<Entrances> FillRelatedEntrancesListUsingLocationRelation(List<Entrances> result) => BGCodeGenUtils.GetRelatedInbound<Entrances>(Entrances._Location, Id, result);
	public List<Quest_Kill_all> FillRelatedQuest_Kill_allListUsingLocationRelation(List<Quest_Kill_all> result) => BGCodeGenUtils.GetRelatedInbound<Quest_Kill_all>(Quest_Kill_all._Location, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4813906483841145583UL,2916551055859798656UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5256612705798366190UL, 17805978858233026978UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Locations(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Locations(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Locations";
		public const string name = "name";
	}
}

[Preserve]
public sealed partial class Quest_Kill_all : BGEntity, IQuests
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5617249186968766316UL,8527001014746565022UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public Locations Location => (Locations) _Location[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5270084110860094871UL, 18221043150238507453UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_Location;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _Location => _ufle12jhs77_Location ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5653548190891933720UL, 739831859566144385UL), () => _ufle12jhs77_Location = null);
	public List<Quests> RelatedQuestsListUsingLinkRelation => BGCodeGenUtils.GetRelatedInbound<Quests>(Quests._Link, Id);
	private Quest_Kill_all() : base(MetaDefault) {}
	private Quest_Kill_all(BGId id) : base(MetaDefault, id) {}
	private Quest_Kill_all(BGMetaEntity meta) : base(meta) {}
	private Quest_Kill_all(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static Quest_Kill_all FindEntity(Predicate<Quest_Kill_all> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<Quest_Kill_all> FindEntities(Predicate<Quest_Kill_all> filter, List<Quest_Kill_all> result=null, Comparison<Quest_Kill_all> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Quest_Kill_all> action, Predicate<Quest_Kill_all> filter=null, Comparison<Quest_Kill_all> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static Quest_Kill_all GetEntity(BGId entityId) => (Quest_Kill_all) MetaDefault.GetEntity(entityId);
	public static Quest_Kill_all GetEntity(int index) => (Quest_Kill_all) MetaDefault[index];
	public static Quest_Kill_all GetEntity(string entityName) => (Quest_Kill_all) MetaDefault.GetEntity(entityName);
	public static Quest_Kill_all NewEntity() => (Quest_Kill_all) MetaDefault.NewEntity();
	public static Quest_Kill_all NewEntity(BGId entityId) => (Quest_Kill_all) MetaDefault.NewEntity(entityId);
	public static Quest_Kill_all NewEntity(Action<Quest_Kill_all> callback) => (Quest_Kill_all) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Quest_Kill_all)entity)));
	public List<Quests> FillRelatedQuestsListUsingLinkRelation(List<Quests> result) => BGCodeGenUtils.GetRelatedInbound<Quests>(Quests._Link, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5617249186968766316UL,8527001014746565022UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5270084110860094871UL, 18221043150238507453UL));
		_ufle12jhs77_Location = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5653548190891933720UL, 739831859566144385UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Location = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Quest_Kill_all(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Quest_Kill_all(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Quest_Kill_all";
		public const string name = "name";
		public const string Location = "Location";
	}
}

[Serializable]
public class RangeTemplates_Row : BGEntityReference<RangeTemplates>
{
	public override BGId TargetMetaId => new BGId(4898656118771152014UL,7349591471542998915UL);
}

[Serializable]
public class ValueSets_Row : BGEntityReference<ValueSets>
{
	public override BGId TargetMetaId => new BGId(5716822476408136107UL,12097655307414520729UL);
}

[Serializable]
public class PropgressionCurves_Row : BGEntityReference<PropgressionCurves>
{
	public override BGId TargetMetaId => new BGId(5441332370735314639UL,4125961409994376623UL);
}

[Serializable]
public class Ranges_Row : BGEntityReference<Ranges>
{
	public override BGId TargetMetaId => new BGId(4635767876034809878UL,4045935601704716205UL);
}

[Serializable]
public class ValueStandarts_Row : BGEntityReference<ValueStandarts>
{
	public override BGId TargetMetaId => new BGId(5091801755773772909UL,4171289196249117874UL);
}

[Serializable]
public class Quest_Kills_Row : BGEntityReference<Quest_Kills>
{
	public override BGId TargetMetaId => new BGId(4634905807947090607UL,15170298109875658939UL);
}

[Serializable]
public class Quests_Row : BGEntityReference<Quests>
{
	public override BGId TargetMetaId => new BGId(5121696395905606201UL,6315781243949073044UL);
}

[Serializable]
public class RewardGold_Row : BGEntityReference<RewardGold>
{
	public override BGId TargetMetaId => new BGId(5588342634143607386UL,7208147853559112364UL);
}

[Serializable]
public class Entrances_Row : BGEntityReference<Entrances>
{
	public override BGId TargetMetaId => new BGId(5053962645146764437UL,7095354471628614050UL);
}

[Serializable]
public class EntranceRelations_Row : BGEntityReference<EntranceRelations>
{
	public override BGId TargetMetaId => new BGId(5665937695245311341UL,14166996636501286334UL);
}

[Serializable]
public class Locations_Row : BGEntityReference<Locations>
{
	public override BGId TargetMetaId => new BGId(4813906483841145583UL,2916551055859798656UL);
}

[Serializable]
public class Quest_Kill_all_Row : BGEntityReference<Quest_Kill_all>
{
	public override BGId TargetMetaId => new BGId(5617249186968766316UL,8527001014746565022UL);
}

[Serializable]
public class IDropItem_Row : BGViewEntityReference<IDropItem>
{
	public override BGId ViewIdConstraint => new BGId(5365962839823872993UL,4887595821240576951UL);
}

[Serializable]
public class IDatabaseSlotData_Row : BGViewEntityReference<IDatabaseSlotData>
{
	public override BGId ViewIdConstraint => new BGId(5672633015894983812UL,4078649096255057307UL);
}

[Serializable]
public class IQuests_Row : BGViewEntityReference<IQuests>
{
	public override BGId ViewIdConstraint => new BGId(4951429683880633383UL,16609171934665023630UL);
}

[Serializable]
public class IReward_Row : BGViewEntityReference<IReward>
{
	public override BGId ViewIdConstraint => new BGId(4840340994631621919UL,607601361245787545UL);
}

[Preserve]
public static class BGCodeGenRuntimeInitializer
{
	[Preserve]
	public static void InitializeCodeGenRuntime()
	{
		RangeTemplates.InitializeCodeGenRuntime();
		ValueSets.InitializeCodeGenRuntime();
		PropgressionCurves.InitializeCodeGenRuntime();
		Ranges.InitializeCodeGenRuntime();
		ValueStandarts.InitializeCodeGenRuntime();
		Quest_Kills.InitializeCodeGenRuntime();
		Quests.InitializeCodeGenRuntime();
		RewardGold.InitializeCodeGenRuntime();
		Entrances.InitializeCodeGenRuntime();
		EntranceRelations.InitializeCodeGenRuntime();
		Locations.InitializeCodeGenRuntime();
		Quest_Kill_all.InitializeCodeGenRuntime();
	}
	[Preserve]
	public static void ReleaseCodeGenRuntime()
	{
		RangeTemplates.ReleaseCodeGenRuntime();
		ValueSets.ReleaseCodeGenRuntime();
		PropgressionCurves.ReleaseCodeGenRuntime();
		Ranges.ReleaseCodeGenRuntime();
		ValueStandarts.ReleaseCodeGenRuntime();
		Quest_Kills.ReleaseCodeGenRuntime();
		Quests.ReleaseCodeGenRuntime();
		RewardGold.ReleaseCodeGenRuntime();
		Entrances.ReleaseCodeGenRuntime();
		EntranceRelations.ReleaseCodeGenRuntime();
		Locations.ReleaseCodeGenRuntime();
		Quest_Kill_all.ReleaseCodeGenRuntime();
	}
}

public partial interface IDropItem  : BGAbstractEntityI
{
	System.String name {get;}
	System.Int32 globalId {get; set;}
}

public partial interface IDatabaseSlotData  : BGAbstractEntityI
{
	System.String name {get;}
	System.Collections.Hashtable Values {get;}
	List<Core.Generated.SlotTagEnum> Tags {get;}
}

public partial interface IQuests  : BGAbstractEntityI
{
	System.String name {get;}
}

public partial interface IReward  : BGAbstractEntityI
{
	System.String name {get;}
	UnityEngine.Sprite Icon {get;}
	System.Int32 Count {get;}
}
#pragma warning restore 414
