//Файл генерируется в GenInitValuesFromBaseValuesSystem
using Core.Components;
using Leopotam.EcsLite;
using Leopotam.EcsLite.Di;

namespace Core.Generated
{
    // @formatter:off
    public class InitValuesFromBaseValuesSystem : IEcsRunSystem
    {
        private readonly EcsFilterInject<Inc<EventInit>> _hasInitFilter;
        
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ActionCostPerSecondValueComponent>>, Exc<ActionCostPerSecondValueComponent>> _baseActionCostPerSecondValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<AddScoreOnDeathValueComponent>>, Exc<AddScoreOnDeathValueComponent>> _baseAddScoreOnDeathValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ArmorPercentValueComponent>>, Exc<ArmorPercentValueComponent>> _baseArmorPercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ArmorPropertyValueComponent>>, Exc<ArmorPropertyValueComponent>> _baseArmorPropertyValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ArmorValueComponent>>, Exc<ArmorValueComponent>> _baseArmorValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<AttackSpeedPercentValueComponent>>, Exc<AttackSpeedPercentValueComponent>> _baseAttackSpeedPercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<AttackSpeedValueComponent>>, Exc<AttackSpeedValueComponent>> _baseAttackSpeedValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageBashValueComponent>>, Exc<BarbDamageBashValueComponent>> _baseBarbDamageBashValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageCleaveValueComponent>>, Exc<BarbDamageCleaveValueComponent>> _baseBarbDamageCleaveValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageFrenzyValueComponent>>, Exc<BarbDamageFrenzyValueComponent>> _baseBarbDamageFrenzyValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageHammerOfTheAncientsValueComponent>>, Exc<BarbDamageHammerOfTheAncientsValueComponent>> _baseBarbDamageHammerOfTheAncientsValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageOverPowerValueComponent>>, Exc<BarbDamageOverPowerValueComponent>> _baseBarbDamageOverPowerValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageRendValueComponent>>, Exc<BarbDamageRendValueComponent>> _baseBarbDamageRendValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageRevengeValueComponent>>, Exc<BarbDamageRevengeValueComponent>> _baseBarbDamageRevengeValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageSeismicSlamValueComponent>>, Exc<BarbDamageSeismicSlamValueComponent>> _baseBarbDamageSeismicSlamValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageWeaponThrowValueComponent>>, Exc<BarbDamageWeaponThrowValueComponent>> _baseBarbDamageWeaponThrowValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbDamageWhirlwindValueComponent>>, Exc<BarbDamageWhirlwindValueComponent>> _baseBarbDamageWhirlwindValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BarbFrenzyStackValueComponent>>, Exc<BarbFrenzyStackValueComponent>> _baseBarbFrenzyStackValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BlockAmountMaxValueComponent>>, Exc<BlockAmountMaxValueComponent>> _baseBlockAmountMaxValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BlockAmountMinValueComponent>>, Exc<BlockAmountMinValueComponent>> _baseBlockAmountMinValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<BlockChanceValueComponent>>, Exc<BlockChanceValueComponent>> _baseBlockChanceValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CriticalChanceValueComponent>>, Exc<CriticalChanceValueComponent>> _baseCriticalChanceValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CriticalDamageValueComponent>>, Exc<CriticalDamageValueComponent>> _baseCriticalDamageValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamageColdValueComponent>>, Exc<DamageColdValueComponent>> _baseDamageColdValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamageFireValueComponent>>, Exc<DamageFireValueComponent>> _baseDamageFireValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamageLightningValueComponent>>, Exc<DamageLightningValueComponent>> _baseDamageLightningValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamageMaxValueComponent>>, Exc<DamageMaxValueComponent>> _baseDamageMaxValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamageMinValueComponent>>, Exc<DamageMinValueComponent>> _baseDamageMinValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamagePercentValueComponent>>, Exc<DamagePercentValueComponent>> _baseDamagePercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamagePhysicalValueComponent>>, Exc<DamagePhysicalValueComponent>> _baseDamagePhysicalValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamagePropertyMaxValueComponent>>, Exc<DamagePropertyMaxValueComponent>> _baseDamagePropertyMaxValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamagePropertyMinValueComponent>>, Exc<DamagePropertyMinValueComponent>> _baseDamagePropertyMinValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamageReflectionPercentValueComponent>>, Exc<DamageReflectionPercentValueComponent>> _baseDamageReflectionPercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DamageValueComponent>>, Exc<DamageValueComponent>> _baseDamageValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<DexterityValueComponent>>, Exc<DexterityValueComponent>> _baseDexterityValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<EnergyMaxValueComponent>>, Exc<EnergyMaxValueComponent>> _baseEnergyMaxValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<EnergyValueComponent>>, Exc<EnergyValueComponent>> _baseEnergyValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<EvasionValueComponent>>, Exc<EvasionValueComponent>> _baseEvasionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ExperienceValueComponent>>, Exc<ExperienceValueComponent>> _baseExperienceValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ExplosionScaleValueComponent>>, Exc<ExplosionScaleValueComponent>> _baseExplosionScaleValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ExtraGoldWhenKillingValueComponent>>, Exc<ExtraGoldWhenKillingValueComponent>> _baseExtraGoldWhenKillingValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<HealingPercentPerSecondValueComponent>>, Exc<HealingPercentPerSecondValueComponent>> _baseHealingPercentPerSecondValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<HealingPerHitValueComponent>>, Exc<HealingPerHitValueComponent>> _baseHealingPerHitValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<HealingPerSecondValueComponent>>, Exc<HealingPerSecondValueComponent>> _baseHealingPerSecondValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<HealingPotionValueComponent>>, Exc<HealingPotionValueComponent>> _baseHealingPotionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<HitPointMaxValueComponent>>, Exc<HitPointMaxValueComponent>> _baseHitPointMaxValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<HitPointPercentValueComponent>>, Exc<HitPointPercentValueComponent>> _baseHitPointPercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<HitPointValueComponent>>, Exc<HitPointValueComponent>> _baseHitPointValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<IncomingDamagePercentValueComponent>>, Exc<IncomingDamagePercentValueComponent>> _baseIncomingDamagePercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<IntelligenceValueComponent>>, Exc<IntelligenceValueComponent>> _baseIntelligenceValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<LevelValueComponent>>, Exc<LevelValueComponent>> _baseLevelValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ManaPointMaxValueComponent>>, Exc<ManaPointMaxValueComponent>> _baseManaPointMaxValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ManaPointRecoveryValueComponent>>, Exc<ManaPointRecoveryValueComponent>> _baseManaPointRecoveryValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ManaPointValueComponent>>, Exc<ManaPointValueComponent>> _baseManaPointValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<MoveSpeedPercentValueComponent>>, Exc<MoveSpeedPercentValueComponent>> _baseMoveSpeedPercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<MoveSpeedValueComponent>>, Exc<MoveSpeedValueComponent>> _baseMoveSpeedValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<RecoveryTimeReductionValueComponent>>, Exc<RecoveryTimeReductionValueComponent>> _baseRecoveryTimeReductionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResistanceAllValueComponent>>, Exc<ResistanceAllValueComponent>> _baseResistanceAllValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceCostsReductionValueComponent>>, Exc<ResourceCostsReductionValueComponent>> _baseResourceCostsReductionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerDamageTakenValueComponent>>, Exc<ResourceRecoveryPerDamageTakenValueComponent>> _baseResourceRecoveryPerDamageTakenValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<SlowdownAnimationValueComponent>>, Exc<SlowdownAnimationValueComponent>> _baseSlowdownAnimationValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<SlowdownMoveValueComponent>>, Exc<SlowdownMoveValueComponent>> _baseSlowdownMoveValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<StrengthValueComponent>>, Exc<StrengthValueComponent>> _baseStrengthValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<VitalityPercentValueComponent>>, Exc<VitalityPercentValueComponent>> _baseVitalityPercentValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<VitalityValueComponent>>, Exc<VitalityValueComponent>> _baseVitalityValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<VulnerabilityCriticalChanceValueComponent>>, Exc<VulnerabilityCriticalChanceValueComponent>> _baseVulnerabilityCriticalChanceValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<WeaponAttackSpeedValueComponent>>, Exc<WeaponAttackSpeedValueComponent>> _baseWeaponAttackSpeedValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkButton1Component>>>, Exc<ChargeCostValueComponent<ActionLinkButton1Component>>> _baseChargeCostValueActionLinkButton1Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkButton2Component>>>, Exc<ChargeCostValueComponent<ActionLinkButton2Component>>> _baseChargeCostValueActionLinkButton2Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkButton3Component>>>, Exc<ChargeCostValueComponent<ActionLinkButton3Component>>> _baseChargeCostValueActionLinkButton3Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkButton4Component>>>, Exc<ChargeCostValueComponent<ActionLinkButton4Component>>> _baseChargeCostValueActionLinkButton4Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkForwardFComponent>>>, Exc<ChargeCostValueComponent<ActionLinkForwardFComponent>>> _baseChargeCostValueActionLinkForwardFFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkMouseLeftComponent>>>, Exc<ChargeCostValueComponent<ActionLinkMouseLeftComponent>>> _baseChargeCostValueActionLinkMouseLeftFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkMouseRightComponent>>>, Exc<ChargeCostValueComponent<ActionLinkMouseRightComponent>>> _baseChargeCostValueActionLinkMouseRightFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkSpaceComponent>>>, Exc<ChargeCostValueComponent<ActionLinkSpaceComponent>>> _baseChargeCostValueActionLinkSpaceFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<ActionLinkSpaceForwardComponent>>>, Exc<ChargeCostValueComponent<ActionLinkSpaceForwardComponent>>> _baseChargeCostValueActionLinkSpaceForwardFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeCostValueComponent<HealingPotionValueComponent>>>, Exc<ChargeCostValueComponent<HealingPotionValueComponent>>> _baseChargeCostValueHealingPotionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton1Component>>>, Exc<ChargeMaxValueComponent<ActionLinkButton1Component>>> _baseChargeMaxValueActionLinkButton1Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton2Component>>>, Exc<ChargeMaxValueComponent<ActionLinkButton2Component>>> _baseChargeMaxValueActionLinkButton2Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton3Component>>>, Exc<ChargeMaxValueComponent<ActionLinkButton3Component>>> _baseChargeMaxValueActionLinkButton3Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton4Component>>>, Exc<ChargeMaxValueComponent<ActionLinkButton4Component>>> _baseChargeMaxValueActionLinkButton4Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkForwardFComponent>>>, Exc<ChargeMaxValueComponent<ActionLinkForwardFComponent>>> _baseChargeMaxValueActionLinkForwardFFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkMouseLeftComponent>>>, Exc<ChargeMaxValueComponent<ActionLinkMouseLeftComponent>>> _baseChargeMaxValueActionLinkMouseLeftFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkMouseRightComponent>>>, Exc<ChargeMaxValueComponent<ActionLinkMouseRightComponent>>> _baseChargeMaxValueActionLinkMouseRightFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkSpaceComponent>>>, Exc<ChargeMaxValueComponent<ActionLinkSpaceComponent>>> _baseChargeMaxValueActionLinkSpaceFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<ActionLinkSpaceForwardComponent>>>, Exc<ChargeMaxValueComponent<ActionLinkSpaceForwardComponent>>> _baseChargeMaxValueActionLinkSpaceForwardFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeMaxValueComponent<HealingPotionValueComponent>>>, Exc<ChargeMaxValueComponent<HealingPotionValueComponent>>> _baseChargeMaxValueHealingPotionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkButton1Component>>>, Exc<ChargeValueComponent<ActionLinkButton1Component>>> _baseChargeValueActionLinkButton1Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkButton2Component>>>, Exc<ChargeValueComponent<ActionLinkButton2Component>>> _baseChargeValueActionLinkButton2Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkButton3Component>>>, Exc<ChargeValueComponent<ActionLinkButton3Component>>> _baseChargeValueActionLinkButton3Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkButton4Component>>>, Exc<ChargeValueComponent<ActionLinkButton4Component>>> _baseChargeValueActionLinkButton4Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkForwardFComponent>>>, Exc<ChargeValueComponent<ActionLinkForwardFComponent>>> _baseChargeValueActionLinkForwardFFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkMouseLeftComponent>>>, Exc<ChargeValueComponent<ActionLinkMouseLeftComponent>>> _baseChargeValueActionLinkMouseLeftFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkMouseRightComponent>>>, Exc<ChargeValueComponent<ActionLinkMouseRightComponent>>> _baseChargeValueActionLinkMouseRightFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkSpaceComponent>>>, Exc<ChargeValueComponent<ActionLinkSpaceComponent>>> _baseChargeValueActionLinkSpaceFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<ActionLinkSpaceForwardComponent>>>, Exc<ChargeValueComponent<ActionLinkSpaceForwardComponent>>> _baseChargeValueActionLinkSpaceForwardFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ChargeValueComponent<HealingPotionValueComponent>>>, Exc<ChargeValueComponent<HealingPotionValueComponent>>> _baseChargeValueHealingPotionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkButton1Component>>>, Exc<CooldownValueComponent<ActionLinkButton1Component>>> _baseCooldownValueActionLinkButton1Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkButton2Component>>>, Exc<CooldownValueComponent<ActionLinkButton2Component>>> _baseCooldownValueActionLinkButton2Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkButton3Component>>>, Exc<CooldownValueComponent<ActionLinkButton3Component>>> _baseCooldownValueActionLinkButton3Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkButton4Component>>>, Exc<CooldownValueComponent<ActionLinkButton4Component>>> _baseCooldownValueActionLinkButton4Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkForwardFComponent>>>, Exc<CooldownValueComponent<ActionLinkForwardFComponent>>> _baseCooldownValueActionLinkForwardFFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkMouseLeftComponent>>>, Exc<CooldownValueComponent<ActionLinkMouseLeftComponent>>> _baseCooldownValueActionLinkMouseLeftFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkMouseRightComponent>>>, Exc<CooldownValueComponent<ActionLinkMouseRightComponent>>> _baseCooldownValueActionLinkMouseRightFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkSpaceComponent>>>, Exc<CooldownValueComponent<ActionLinkSpaceComponent>>> _baseCooldownValueActionLinkSpaceFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<ActionLinkSpaceForwardComponent>>>, Exc<CooldownValueComponent<ActionLinkSpaceForwardComponent>>> _baseCooldownValueActionLinkSpaceForwardFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CooldownValueComponent<HealingPotionValueComponent>>>, Exc<CooldownValueComponent<HealingPotionValueComponent>>> _baseCooldownValueHealingPotionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkButton1Component>>>, Exc<CostValueComponent<ActionLinkButton1Component>>> _baseCostValueActionLinkButton1Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkButton2Component>>>, Exc<CostValueComponent<ActionLinkButton2Component>>> _baseCostValueActionLinkButton2Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkButton3Component>>>, Exc<CostValueComponent<ActionLinkButton3Component>>> _baseCostValueActionLinkButton3Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkButton4Component>>>, Exc<CostValueComponent<ActionLinkButton4Component>>> _baseCostValueActionLinkButton4Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkForwardFComponent>>>, Exc<CostValueComponent<ActionLinkForwardFComponent>>> _baseCostValueActionLinkForwardFFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkMouseLeftComponent>>>, Exc<CostValueComponent<ActionLinkMouseLeftComponent>>> _baseCostValueActionLinkMouseLeftFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkMouseRightComponent>>>, Exc<CostValueComponent<ActionLinkMouseRightComponent>>> _baseCostValueActionLinkMouseRightFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkSpaceComponent>>>, Exc<CostValueComponent<ActionLinkSpaceComponent>>> _baseCostValueActionLinkSpaceFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<CostValueComponent<ActionLinkSpaceForwardComponent>>>, Exc<CostValueComponent<ActionLinkSpaceForwardComponent>>> _baseCostValueActionLinkSpaceForwardFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton1Component>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkButton1Component>>> _baseResourceRecoveryPerHitValueActionLinkButton1Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton2Component>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkButton2Component>>> _baseResourceRecoveryPerHitValueActionLinkButton2Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton3Component>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkButton3Component>>> _baseResourceRecoveryPerHitValueActionLinkButton3Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton4Component>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkButton4Component>>> _baseResourceRecoveryPerHitValueActionLinkButton4Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkForwardFComponent>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkForwardFComponent>>> _baseResourceRecoveryPerHitValueActionLinkForwardFFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkMouseLeftComponent>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkMouseLeftComponent>>> _baseResourceRecoveryPerHitValueActionLinkMouseLeftFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkMouseRightComponent>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkMouseRightComponent>>> _baseResourceRecoveryPerHitValueActionLinkMouseRightFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceComponent>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceComponent>>> _baseResourceRecoveryPerHitValueActionLinkSpaceFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceForwardComponent>>>, Exc<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceForwardComponent>>> _baseResourceRecoveryPerHitValueActionLinkSpaceForwardFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerHitValueComponent<HealingPotionValueComponent>>>, Exc<ResourceRecoveryPerHitValueComponent<HealingPotionValueComponent>>> _baseResourceRecoveryPerHitValueHealingPotionValueFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton1Component>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkButton1Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton1Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton2Component>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkButton2Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton2Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton3Component>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkButton3Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton3Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton4Component>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkButton4Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton4Filter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkForwardFComponent>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkForwardFComponent>>> _baseResourceRecoveryPerUsingValueActionLinkForwardFFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseLeftComponent>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseLeftComponent>>> _baseResourceRecoveryPerUsingValueActionLinkMouseLeftFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseRightComponent>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseRightComponent>>> _baseResourceRecoveryPerUsingValueActionLinkMouseRightFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceComponent>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceComponent>>> _baseResourceRecoveryPerUsingValueActionLinkSpaceFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceForwardComponent>>>, Exc<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceForwardComponent>>> _baseResourceRecoveryPerUsingValueActionLinkSpaceForwardFilter;
        private readonly EcsFilterInject<Inc<EventInit, BaseValueComponent<ResourceRecoveryPerUsingValueComponent<HealingPotionValueComponent>>>, Exc<ResourceRecoveryPerUsingValueComponent<HealingPotionValueComponent>>> _baseResourceRecoveryPerUsingValueHealingPotionValueFilter;

        private readonly EcsPoolInject<BaseValueComponent<ActionCostPerSecondValueComponent>> _baseActionCostPerSecondValuePool;
        private readonly EcsPoolInject<ActionCostPerSecondValueComponent> _ActionCostPerSecondValuePool;
        private readonly EcsPoolInject<BaseValueComponent<AddScoreOnDeathValueComponent>> _baseAddScoreOnDeathValuePool;
        private readonly EcsPoolInject<AddScoreOnDeathValueComponent> _AddScoreOnDeathValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ArmorPercentValueComponent>> _baseArmorPercentValuePool;
        private readonly EcsPoolInject<ArmorPercentValueComponent> _ArmorPercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ArmorPropertyValueComponent>> _baseArmorPropertyValuePool;
        private readonly EcsPoolInject<ArmorPropertyValueComponent> _ArmorPropertyValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ArmorValueComponent>> _baseArmorValuePool;
        private readonly EcsPoolInject<ArmorValueComponent> _ArmorValuePool;
        private readonly EcsPoolInject<BaseValueComponent<AttackSpeedPercentValueComponent>> _baseAttackSpeedPercentValuePool;
        private readonly EcsPoolInject<AttackSpeedPercentValueComponent> _AttackSpeedPercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<AttackSpeedValueComponent>> _baseAttackSpeedValuePool;
        private readonly EcsPoolInject<AttackSpeedValueComponent> _AttackSpeedValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageBashValueComponent>> _baseBarbDamageBashValuePool;
        private readonly EcsPoolInject<BarbDamageBashValueComponent> _BarbDamageBashValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageCleaveValueComponent>> _baseBarbDamageCleaveValuePool;
        private readonly EcsPoolInject<BarbDamageCleaveValueComponent> _BarbDamageCleaveValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageFrenzyValueComponent>> _baseBarbDamageFrenzyValuePool;
        private readonly EcsPoolInject<BarbDamageFrenzyValueComponent> _BarbDamageFrenzyValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageHammerOfTheAncientsValueComponent>> _baseBarbDamageHammerOfTheAncientsValuePool;
        private readonly EcsPoolInject<BarbDamageHammerOfTheAncientsValueComponent> _BarbDamageHammerOfTheAncientsValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageOverPowerValueComponent>> _baseBarbDamageOverPowerValuePool;
        private readonly EcsPoolInject<BarbDamageOverPowerValueComponent> _BarbDamageOverPowerValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageRendValueComponent>> _baseBarbDamageRendValuePool;
        private readonly EcsPoolInject<BarbDamageRendValueComponent> _BarbDamageRendValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageRevengeValueComponent>> _baseBarbDamageRevengeValuePool;
        private readonly EcsPoolInject<BarbDamageRevengeValueComponent> _BarbDamageRevengeValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageSeismicSlamValueComponent>> _baseBarbDamageSeismicSlamValuePool;
        private readonly EcsPoolInject<BarbDamageSeismicSlamValueComponent> _BarbDamageSeismicSlamValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageWeaponThrowValueComponent>> _baseBarbDamageWeaponThrowValuePool;
        private readonly EcsPoolInject<BarbDamageWeaponThrowValueComponent> _BarbDamageWeaponThrowValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbDamageWhirlwindValueComponent>> _baseBarbDamageWhirlwindValuePool;
        private readonly EcsPoolInject<BarbDamageWhirlwindValueComponent> _BarbDamageWhirlwindValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BarbFrenzyStackValueComponent>> _baseBarbFrenzyStackValuePool;
        private readonly EcsPoolInject<BarbFrenzyStackValueComponent> _BarbFrenzyStackValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BlockAmountMaxValueComponent>> _baseBlockAmountMaxValuePool;
        private readonly EcsPoolInject<BlockAmountMaxValueComponent> _BlockAmountMaxValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BlockAmountMinValueComponent>> _baseBlockAmountMinValuePool;
        private readonly EcsPoolInject<BlockAmountMinValueComponent> _BlockAmountMinValuePool;
        private readonly EcsPoolInject<BaseValueComponent<BlockChanceValueComponent>> _baseBlockChanceValuePool;
        private readonly EcsPoolInject<BlockChanceValueComponent> _BlockChanceValuePool;
        private readonly EcsPoolInject<BaseValueComponent<CriticalChanceValueComponent>> _baseCriticalChanceValuePool;
        private readonly EcsPoolInject<CriticalChanceValueComponent> _CriticalChanceValuePool;
        private readonly EcsPoolInject<BaseValueComponent<CriticalDamageValueComponent>> _baseCriticalDamageValuePool;
        private readonly EcsPoolInject<CriticalDamageValueComponent> _CriticalDamageValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamageColdValueComponent>> _baseDamageColdValuePool;
        private readonly EcsPoolInject<DamageColdValueComponent> _DamageColdValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamageFireValueComponent>> _baseDamageFireValuePool;
        private readonly EcsPoolInject<DamageFireValueComponent> _DamageFireValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamageLightningValueComponent>> _baseDamageLightningValuePool;
        private readonly EcsPoolInject<DamageLightningValueComponent> _DamageLightningValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamageMaxValueComponent>> _baseDamageMaxValuePool;
        private readonly EcsPoolInject<DamageMaxValueComponent> _DamageMaxValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamageMinValueComponent>> _baseDamageMinValuePool;
        private readonly EcsPoolInject<DamageMinValueComponent> _DamageMinValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamagePercentValueComponent>> _baseDamagePercentValuePool;
        private readonly EcsPoolInject<DamagePercentValueComponent> _DamagePercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamagePhysicalValueComponent>> _baseDamagePhysicalValuePool;
        private readonly EcsPoolInject<DamagePhysicalValueComponent> _DamagePhysicalValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamagePropertyMaxValueComponent>> _baseDamagePropertyMaxValuePool;
        private readonly EcsPoolInject<DamagePropertyMaxValueComponent> _DamagePropertyMaxValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamagePropertyMinValueComponent>> _baseDamagePropertyMinValuePool;
        private readonly EcsPoolInject<DamagePropertyMinValueComponent> _DamagePropertyMinValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamageReflectionPercentValueComponent>> _baseDamageReflectionPercentValuePool;
        private readonly EcsPoolInject<DamageReflectionPercentValueComponent> _DamageReflectionPercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DamageValueComponent>> _baseDamageValuePool;
        private readonly EcsPoolInject<DamageValueComponent> _DamageValuePool;
        private readonly EcsPoolInject<BaseValueComponent<DexterityValueComponent>> _baseDexterityValuePool;
        private readonly EcsPoolInject<DexterityValueComponent> _DexterityValuePool;
        private readonly EcsPoolInject<BaseValueComponent<EnergyMaxValueComponent>> _baseEnergyMaxValuePool;
        private readonly EcsPoolInject<EnergyMaxValueComponent> _EnergyMaxValuePool;
        private readonly EcsPoolInject<BaseValueComponent<EnergyValueComponent>> _baseEnergyValuePool;
        private readonly EcsPoolInject<EnergyValueComponent> _EnergyValuePool;
        private readonly EcsPoolInject<BaseValueComponent<EvasionValueComponent>> _baseEvasionValuePool;
        private readonly EcsPoolInject<EvasionValueComponent> _EvasionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ExperienceValueComponent>> _baseExperienceValuePool;
        private readonly EcsPoolInject<ExperienceValueComponent> _ExperienceValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ExplosionScaleValueComponent>> _baseExplosionScaleValuePool;
        private readonly EcsPoolInject<ExplosionScaleValueComponent> _ExplosionScaleValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ExtraGoldWhenKillingValueComponent>> _baseExtraGoldWhenKillingValuePool;
        private readonly EcsPoolInject<ExtraGoldWhenKillingValueComponent> _ExtraGoldWhenKillingValuePool;
        private readonly EcsPoolInject<BaseValueComponent<HealingPercentPerSecondValueComponent>> _baseHealingPercentPerSecondValuePool;
        private readonly EcsPoolInject<HealingPercentPerSecondValueComponent> _HealingPercentPerSecondValuePool;
        private readonly EcsPoolInject<BaseValueComponent<HealingPerHitValueComponent>> _baseHealingPerHitValuePool;
        private readonly EcsPoolInject<HealingPerHitValueComponent> _HealingPerHitValuePool;
        private readonly EcsPoolInject<BaseValueComponent<HealingPerSecondValueComponent>> _baseHealingPerSecondValuePool;
        private readonly EcsPoolInject<HealingPerSecondValueComponent> _HealingPerSecondValuePool;
        private readonly EcsPoolInject<BaseValueComponent<HealingPotionValueComponent>> _baseHealingPotionValuePool;
        private readonly EcsPoolInject<HealingPotionValueComponent> _HealingPotionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<HitPointMaxValueComponent>> _baseHitPointMaxValuePool;
        private readonly EcsPoolInject<HitPointMaxValueComponent> _HitPointMaxValuePool;
        private readonly EcsPoolInject<BaseValueComponent<HitPointPercentValueComponent>> _baseHitPointPercentValuePool;
        private readonly EcsPoolInject<HitPointPercentValueComponent> _HitPointPercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<HitPointValueComponent>> _baseHitPointValuePool;
        private readonly EcsPoolInject<HitPointValueComponent> _HitPointValuePool;
        private readonly EcsPoolInject<BaseValueComponent<IncomingDamagePercentValueComponent>> _baseIncomingDamagePercentValuePool;
        private readonly EcsPoolInject<IncomingDamagePercentValueComponent> _IncomingDamagePercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<IntelligenceValueComponent>> _baseIntelligenceValuePool;
        private readonly EcsPoolInject<IntelligenceValueComponent> _IntelligenceValuePool;
        private readonly EcsPoolInject<BaseValueComponent<LevelValueComponent>> _baseLevelValuePool;
        private readonly EcsPoolInject<LevelValueComponent> _LevelValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ManaPointMaxValueComponent>> _baseManaPointMaxValuePool;
        private readonly EcsPoolInject<ManaPointMaxValueComponent> _ManaPointMaxValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ManaPointRecoveryValueComponent>> _baseManaPointRecoveryValuePool;
        private readonly EcsPoolInject<ManaPointRecoveryValueComponent> _ManaPointRecoveryValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ManaPointValueComponent>> _baseManaPointValuePool;
        private readonly EcsPoolInject<ManaPointValueComponent> _ManaPointValuePool;
        private readonly EcsPoolInject<BaseValueComponent<MoveSpeedPercentValueComponent>> _baseMoveSpeedPercentValuePool;
        private readonly EcsPoolInject<MoveSpeedPercentValueComponent> _MoveSpeedPercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<MoveSpeedValueComponent>> _baseMoveSpeedValuePool;
        private readonly EcsPoolInject<MoveSpeedValueComponent> _MoveSpeedValuePool;
        private readonly EcsPoolInject<BaseValueComponent<RecoveryTimeReductionValueComponent>> _baseRecoveryTimeReductionValuePool;
        private readonly EcsPoolInject<RecoveryTimeReductionValueComponent> _RecoveryTimeReductionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ResistanceAllValueComponent>> _baseResistanceAllValuePool;
        private readonly EcsPoolInject<ResistanceAllValueComponent> _ResistanceAllValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceCostsReductionValueComponent>> _baseResourceCostsReductionValuePool;
        private readonly EcsPoolInject<ResourceCostsReductionValueComponent> _ResourceCostsReductionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerDamageTakenValueComponent>> _baseResourceRecoveryPerDamageTakenValuePool;
        private readonly EcsPoolInject<ResourceRecoveryPerDamageTakenValueComponent> _ResourceRecoveryPerDamageTakenValuePool;
        private readonly EcsPoolInject<BaseValueComponent<SlowdownAnimationValueComponent>> _baseSlowdownAnimationValuePool;
        private readonly EcsPoolInject<SlowdownAnimationValueComponent> _SlowdownAnimationValuePool;
        private readonly EcsPoolInject<BaseValueComponent<SlowdownMoveValueComponent>> _baseSlowdownMoveValuePool;
        private readonly EcsPoolInject<SlowdownMoveValueComponent> _SlowdownMoveValuePool;
        private readonly EcsPoolInject<BaseValueComponent<StrengthValueComponent>> _baseStrengthValuePool;
        private readonly EcsPoolInject<StrengthValueComponent> _StrengthValuePool;
        private readonly EcsPoolInject<BaseValueComponent<VitalityPercentValueComponent>> _baseVitalityPercentValuePool;
        private readonly EcsPoolInject<VitalityPercentValueComponent> _VitalityPercentValuePool;
        private readonly EcsPoolInject<BaseValueComponent<VitalityValueComponent>> _baseVitalityValuePool;
        private readonly EcsPoolInject<VitalityValueComponent> _VitalityValuePool;
        private readonly EcsPoolInject<BaseValueComponent<VulnerabilityCriticalChanceValueComponent>> _baseVulnerabilityCriticalChanceValuePool;
        private readonly EcsPoolInject<VulnerabilityCriticalChanceValueComponent> _VulnerabilityCriticalChanceValuePool;
        private readonly EcsPoolInject<BaseValueComponent<WeaponAttackSpeedValueComponent>> _baseWeaponAttackSpeedValuePool;
        private readonly EcsPoolInject<WeaponAttackSpeedValueComponent> _WeaponAttackSpeedValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkButton1Component>>> _baseChargeCostValueActionLinkButton1Pool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkButton1Component>> _ChargeCostValueActionLinkButton1Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkButton2Component>>> _baseChargeCostValueActionLinkButton2Pool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkButton2Component>> _ChargeCostValueActionLinkButton2Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkButton3Component>>> _baseChargeCostValueActionLinkButton3Pool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkButton3Component>> _ChargeCostValueActionLinkButton3Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkButton4Component>>> _baseChargeCostValueActionLinkButton4Pool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkButton4Component>> _ChargeCostValueActionLinkButton4Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkForwardFComponent>>> _baseChargeCostValueActionLinkForwardFPool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkForwardFComponent>> _ChargeCostValueActionLinkForwardFPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkMouseLeftComponent>>> _baseChargeCostValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkMouseLeftComponent>> _ChargeCostValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkMouseRightComponent>>> _baseChargeCostValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkMouseRightComponent>> _ChargeCostValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkSpaceComponent>>> _baseChargeCostValueActionLinkSpacePool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkSpaceComponent>> _ChargeCostValueActionLinkSpacePool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<ActionLinkSpaceForwardComponent>>> _baseChargeCostValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<ChargeCostValueComponent<ActionLinkSpaceForwardComponent>> _ChargeCostValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeCostValueComponent<HealingPotionValueComponent>>> _baseChargeCostValueHealingPotionValuePool;
        private readonly EcsPoolInject<ChargeCostValueComponent<HealingPotionValueComponent>> _ChargeCostValueHealingPotionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton1Component>>> _baseChargeMaxValueActionLinkButton1Pool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkButton1Component>> _ChargeMaxValueActionLinkButton1Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton2Component>>> _baseChargeMaxValueActionLinkButton2Pool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkButton2Component>> _ChargeMaxValueActionLinkButton2Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton3Component>>> _baseChargeMaxValueActionLinkButton3Pool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkButton3Component>> _ChargeMaxValueActionLinkButton3Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkButton4Component>>> _baseChargeMaxValueActionLinkButton4Pool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkButton4Component>> _ChargeMaxValueActionLinkButton4Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkForwardFComponent>>> _baseChargeMaxValueActionLinkForwardFPool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkForwardFComponent>> _ChargeMaxValueActionLinkForwardFPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkMouseLeftComponent>>> _baseChargeMaxValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkMouseLeftComponent>> _ChargeMaxValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkMouseRightComponent>>> _baseChargeMaxValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkMouseRightComponent>> _ChargeMaxValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkSpaceComponent>>> _baseChargeMaxValueActionLinkSpacePool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkSpaceComponent>> _ChargeMaxValueActionLinkSpacePool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<ActionLinkSpaceForwardComponent>>> _baseChargeMaxValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<ActionLinkSpaceForwardComponent>> _ChargeMaxValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeMaxValueComponent<HealingPotionValueComponent>>> _baseChargeMaxValueHealingPotionValuePool;
        private readonly EcsPoolInject<ChargeMaxValueComponent<HealingPotionValueComponent>> _ChargeMaxValueHealingPotionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkButton1Component>>> _baseChargeValueActionLinkButton1Pool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkButton1Component>> _ChargeValueActionLinkButton1Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkButton2Component>>> _baseChargeValueActionLinkButton2Pool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkButton2Component>> _ChargeValueActionLinkButton2Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkButton3Component>>> _baseChargeValueActionLinkButton3Pool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkButton3Component>> _ChargeValueActionLinkButton3Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkButton4Component>>> _baseChargeValueActionLinkButton4Pool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkButton4Component>> _ChargeValueActionLinkButton4Pool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkForwardFComponent>>> _baseChargeValueActionLinkForwardFPool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkForwardFComponent>> _ChargeValueActionLinkForwardFPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkMouseLeftComponent>>> _baseChargeValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkMouseLeftComponent>> _ChargeValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkMouseRightComponent>>> _baseChargeValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkMouseRightComponent>> _ChargeValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkSpaceComponent>>> _baseChargeValueActionLinkSpacePool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkSpaceComponent>> _ChargeValueActionLinkSpacePool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<ActionLinkSpaceForwardComponent>>> _baseChargeValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<ChargeValueComponent<ActionLinkSpaceForwardComponent>> _ChargeValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<BaseValueComponent<ChargeValueComponent<HealingPotionValueComponent>>> _baseChargeValueHealingPotionValuePool;
        private readonly EcsPoolInject<ChargeValueComponent<HealingPotionValueComponent>> _ChargeValueHealingPotionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkButton1Component>>> _baseCooldownValueActionLinkButton1Pool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkButton1Component>> _CooldownValueActionLinkButton1Pool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkButton2Component>>> _baseCooldownValueActionLinkButton2Pool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkButton2Component>> _CooldownValueActionLinkButton2Pool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkButton3Component>>> _baseCooldownValueActionLinkButton3Pool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkButton3Component>> _CooldownValueActionLinkButton3Pool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkButton4Component>>> _baseCooldownValueActionLinkButton4Pool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkButton4Component>> _CooldownValueActionLinkButton4Pool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkForwardFComponent>>> _baseCooldownValueActionLinkForwardFPool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkForwardFComponent>> _CooldownValueActionLinkForwardFPool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkMouseLeftComponent>>> _baseCooldownValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkMouseLeftComponent>> _CooldownValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkMouseRightComponent>>> _baseCooldownValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkMouseRightComponent>> _CooldownValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkSpaceComponent>>> _baseCooldownValueActionLinkSpacePool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkSpaceComponent>> _CooldownValueActionLinkSpacePool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<ActionLinkSpaceForwardComponent>>> _baseCooldownValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<CooldownValueComponent<ActionLinkSpaceForwardComponent>> _CooldownValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<BaseValueComponent<CooldownValueComponent<HealingPotionValueComponent>>> _baseCooldownValueHealingPotionValuePool;
        private readonly EcsPoolInject<CooldownValueComponent<HealingPotionValueComponent>> _CooldownValueHealingPotionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkButton1Component>>> _baseCostValueActionLinkButton1Pool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkButton1Component>> _CostValueActionLinkButton1Pool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkButton2Component>>> _baseCostValueActionLinkButton2Pool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkButton2Component>> _CostValueActionLinkButton2Pool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkButton3Component>>> _baseCostValueActionLinkButton3Pool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkButton3Component>> _CostValueActionLinkButton3Pool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkButton4Component>>> _baseCostValueActionLinkButton4Pool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkButton4Component>> _CostValueActionLinkButton4Pool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkForwardFComponent>>> _baseCostValueActionLinkForwardFPool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkForwardFComponent>> _CostValueActionLinkForwardFPool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkMouseLeftComponent>>> _baseCostValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkMouseLeftComponent>> _CostValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkMouseRightComponent>>> _baseCostValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkMouseRightComponent>> _CostValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkSpaceComponent>>> _baseCostValueActionLinkSpacePool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkSpaceComponent>> _CostValueActionLinkSpacePool;
        private readonly EcsPoolInject<BaseValueComponent<CostValueComponent<ActionLinkSpaceForwardComponent>>> _baseCostValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<CostValueComponent<ActionLinkSpaceForwardComponent>> _CostValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton1Component>>> _baseResourceRecoveryPerHitValueActionLinkButton1Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkButton1Component>> _ResourceRecoveryPerHitValueActionLinkButton1Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton2Component>>> _baseResourceRecoveryPerHitValueActionLinkButton2Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkButton2Component>> _ResourceRecoveryPerHitValueActionLinkButton2Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton3Component>>> _baseResourceRecoveryPerHitValueActionLinkButton3Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkButton3Component>> _ResourceRecoveryPerHitValueActionLinkButton3Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkButton4Component>>> _baseResourceRecoveryPerHitValueActionLinkButton4Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkButton4Component>> _ResourceRecoveryPerHitValueActionLinkButton4Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkForwardFComponent>>> _baseResourceRecoveryPerHitValueActionLinkForwardFPool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkForwardFComponent>> _ResourceRecoveryPerHitValueActionLinkForwardFPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkMouseLeftComponent>>> _baseResourceRecoveryPerHitValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkMouseLeftComponent>> _ResourceRecoveryPerHitValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkMouseRightComponent>>> _baseResourceRecoveryPerHitValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkMouseRightComponent>> _ResourceRecoveryPerHitValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceComponent>>> _baseResourceRecoveryPerHitValueActionLinkSpacePool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceComponent>> _ResourceRecoveryPerHitValueActionLinkSpacePool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceForwardComponent>>> _baseResourceRecoveryPerHitValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceForwardComponent>> _ResourceRecoveryPerHitValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerHitValueComponent<HealingPotionValueComponent>>> _baseResourceRecoveryPerHitValueHealingPotionValuePool;
        private readonly EcsPoolInject<ResourceRecoveryPerHitValueComponent<HealingPotionValueComponent>> _ResourceRecoveryPerHitValueHealingPotionValuePool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton1Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton1Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkButton1Component>> _ResourceRecoveryPerUsingValueActionLinkButton1Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton2Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton2Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkButton2Component>> _ResourceRecoveryPerUsingValueActionLinkButton2Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton3Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton3Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkButton3Component>> _ResourceRecoveryPerUsingValueActionLinkButton3Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkButton4Component>>> _baseResourceRecoveryPerUsingValueActionLinkButton4Pool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkButton4Component>> _ResourceRecoveryPerUsingValueActionLinkButton4Pool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkForwardFComponent>>> _baseResourceRecoveryPerUsingValueActionLinkForwardFPool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkForwardFComponent>> _ResourceRecoveryPerUsingValueActionLinkForwardFPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseLeftComponent>>> _baseResourceRecoveryPerUsingValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseLeftComponent>> _ResourceRecoveryPerUsingValueActionLinkMouseLeftPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseRightComponent>>> _baseResourceRecoveryPerUsingValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseRightComponent>> _ResourceRecoveryPerUsingValueActionLinkMouseRightPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceComponent>>> _baseResourceRecoveryPerUsingValueActionLinkSpacePool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceComponent>> _ResourceRecoveryPerUsingValueActionLinkSpacePool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceForwardComponent>>> _baseResourceRecoveryPerUsingValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceForwardComponent>> _ResourceRecoveryPerUsingValueActionLinkSpaceForwardPool;
        private readonly EcsPoolInject<BaseValueComponent<ResourceRecoveryPerUsingValueComponent<HealingPotionValueComponent>>> _baseResourceRecoveryPerUsingValueHealingPotionValuePool;
        private readonly EcsPoolInject<ResourceRecoveryPerUsingValueComponent<HealingPotionValueComponent>> _ResourceRecoveryPerUsingValueHealingPotionValuePool;

        public void Run(IEcsSystems systems)
        {
            if (_hasInitFilter.Value.GetEntitiesCount() == 0)
                return;
            
            foreach (var i in _baseActionCostPerSecondValueFilter.Value) _ActionCostPerSecondValuePool.Value.Add(i).value = _baseActionCostPerSecondValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseAddScoreOnDeathValueFilter.Value) _AddScoreOnDeathValuePool.Value.Add(i).value = _baseAddScoreOnDeathValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseArmorPercentValueFilter.Value) _ArmorPercentValuePool.Value.Add(i).value = _baseArmorPercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseArmorPropertyValueFilter.Value) _ArmorPropertyValuePool.Value.Add(i).value = _baseArmorPropertyValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseArmorValueFilter.Value) _ArmorValuePool.Value.Add(i).value = _baseArmorValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseAttackSpeedPercentValueFilter.Value) _AttackSpeedPercentValuePool.Value.Add(i).value = _baseAttackSpeedPercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseAttackSpeedValueFilter.Value) _AttackSpeedValuePool.Value.Add(i).value = _baseAttackSpeedValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageBashValueFilter.Value) _BarbDamageBashValuePool.Value.Add(i).value = _baseBarbDamageBashValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageCleaveValueFilter.Value) _BarbDamageCleaveValuePool.Value.Add(i).value = _baseBarbDamageCleaveValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageFrenzyValueFilter.Value) _BarbDamageFrenzyValuePool.Value.Add(i).value = _baseBarbDamageFrenzyValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageHammerOfTheAncientsValueFilter.Value) _BarbDamageHammerOfTheAncientsValuePool.Value.Add(i).value = _baseBarbDamageHammerOfTheAncientsValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageOverPowerValueFilter.Value) _BarbDamageOverPowerValuePool.Value.Add(i).value = _baseBarbDamageOverPowerValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageRendValueFilter.Value) _BarbDamageRendValuePool.Value.Add(i).value = _baseBarbDamageRendValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageRevengeValueFilter.Value) _BarbDamageRevengeValuePool.Value.Add(i).value = _baseBarbDamageRevengeValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageSeismicSlamValueFilter.Value) _BarbDamageSeismicSlamValuePool.Value.Add(i).value = _baseBarbDamageSeismicSlamValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageWeaponThrowValueFilter.Value) _BarbDamageWeaponThrowValuePool.Value.Add(i).value = _baseBarbDamageWeaponThrowValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbDamageWhirlwindValueFilter.Value) _BarbDamageWhirlwindValuePool.Value.Add(i).value = _baseBarbDamageWhirlwindValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBarbFrenzyStackValueFilter.Value) _BarbFrenzyStackValuePool.Value.Add(i).value = _baseBarbFrenzyStackValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBlockAmountMaxValueFilter.Value) _BlockAmountMaxValuePool.Value.Add(i).value = _baseBlockAmountMaxValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBlockAmountMinValueFilter.Value) _BlockAmountMinValuePool.Value.Add(i).value = _baseBlockAmountMinValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseBlockChanceValueFilter.Value) _BlockChanceValuePool.Value.Add(i).value = _baseBlockChanceValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseCriticalChanceValueFilter.Value) _CriticalChanceValuePool.Value.Add(i).value = _baseCriticalChanceValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseCriticalDamageValueFilter.Value) _CriticalDamageValuePool.Value.Add(i).value = _baseCriticalDamageValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamageColdValueFilter.Value) _DamageColdValuePool.Value.Add(i).value = _baseDamageColdValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamageFireValueFilter.Value) _DamageFireValuePool.Value.Add(i).value = _baseDamageFireValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamageLightningValueFilter.Value) _DamageLightningValuePool.Value.Add(i).value = _baseDamageLightningValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamageMaxValueFilter.Value) _DamageMaxValuePool.Value.Add(i).value = _baseDamageMaxValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamageMinValueFilter.Value) _DamageMinValuePool.Value.Add(i).value = _baseDamageMinValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamagePercentValueFilter.Value) _DamagePercentValuePool.Value.Add(i).value = _baseDamagePercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamagePhysicalValueFilter.Value) _DamagePhysicalValuePool.Value.Add(i).value = _baseDamagePhysicalValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamagePropertyMaxValueFilter.Value) _DamagePropertyMaxValuePool.Value.Add(i).value = _baseDamagePropertyMaxValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamagePropertyMinValueFilter.Value) _DamagePropertyMinValuePool.Value.Add(i).value = _baseDamagePropertyMinValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamageReflectionPercentValueFilter.Value) _DamageReflectionPercentValuePool.Value.Add(i).value = _baseDamageReflectionPercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDamageValueFilter.Value) _DamageValuePool.Value.Add(i).value = _baseDamageValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseDexterityValueFilter.Value) _DexterityValuePool.Value.Add(i).value = _baseDexterityValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseEnergyMaxValueFilter.Value) _EnergyMaxValuePool.Value.Add(i).value = _baseEnergyMaxValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseEnergyValueFilter.Value) _EnergyValuePool.Value.Add(i).value = _baseEnergyValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseEvasionValueFilter.Value) _EvasionValuePool.Value.Add(i).value = _baseEvasionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseExperienceValueFilter.Value) _ExperienceValuePool.Value.Add(i).value = _baseExperienceValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseExplosionScaleValueFilter.Value) _ExplosionScaleValuePool.Value.Add(i).value = _baseExplosionScaleValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseExtraGoldWhenKillingValueFilter.Value) _ExtraGoldWhenKillingValuePool.Value.Add(i).value = _baseExtraGoldWhenKillingValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseHealingPercentPerSecondValueFilter.Value) _HealingPercentPerSecondValuePool.Value.Add(i).value = _baseHealingPercentPerSecondValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseHealingPerHitValueFilter.Value) _HealingPerHitValuePool.Value.Add(i).value = _baseHealingPerHitValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseHealingPerSecondValueFilter.Value) _HealingPerSecondValuePool.Value.Add(i).value = _baseHealingPerSecondValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseHealingPotionValueFilter.Value) _HealingPotionValuePool.Value.Add(i).value = _baseHealingPotionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseHitPointMaxValueFilter.Value) _HitPointMaxValuePool.Value.Add(i).value = _baseHitPointMaxValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseHitPointPercentValueFilter.Value) _HitPointPercentValuePool.Value.Add(i).value = _baseHitPointPercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseHitPointValueFilter.Value) _HitPointValuePool.Value.Add(i).value = _baseHitPointValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseIncomingDamagePercentValueFilter.Value) _IncomingDamagePercentValuePool.Value.Add(i).value = _baseIncomingDamagePercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseIntelligenceValueFilter.Value) _IntelligenceValuePool.Value.Add(i).value = _baseIntelligenceValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseLevelValueFilter.Value) _LevelValuePool.Value.Add(i).value = _baseLevelValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseManaPointMaxValueFilter.Value) _ManaPointMaxValuePool.Value.Add(i).value = _baseManaPointMaxValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseManaPointRecoveryValueFilter.Value) _ManaPointRecoveryValuePool.Value.Add(i).value = _baseManaPointRecoveryValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseManaPointValueFilter.Value) _ManaPointValuePool.Value.Add(i).value = _baseManaPointValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseMoveSpeedPercentValueFilter.Value) _MoveSpeedPercentValuePool.Value.Add(i).value = _baseMoveSpeedPercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseMoveSpeedValueFilter.Value) _MoveSpeedValuePool.Value.Add(i).value = _baseMoveSpeedValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseRecoveryTimeReductionValueFilter.Value) _RecoveryTimeReductionValuePool.Value.Add(i).value = _baseRecoveryTimeReductionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseResistanceAllValueFilter.Value) _ResistanceAllValuePool.Value.Add(i).value = _baseResistanceAllValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceCostsReductionValueFilter.Value) _ResourceCostsReductionValuePool.Value.Add(i).value = _baseResourceCostsReductionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerDamageTakenValueFilter.Value) _ResourceRecoveryPerDamageTakenValuePool.Value.Add(i).value = _baseResourceRecoveryPerDamageTakenValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseSlowdownAnimationValueFilter.Value) _SlowdownAnimationValuePool.Value.Add(i).value = _baseSlowdownAnimationValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseSlowdownMoveValueFilter.Value) _SlowdownMoveValuePool.Value.Add(i).value = _baseSlowdownMoveValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseStrengthValueFilter.Value) _StrengthValuePool.Value.Add(i).value = _baseStrengthValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseVitalityPercentValueFilter.Value) _VitalityPercentValuePool.Value.Add(i).value = _baseVitalityPercentValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseVitalityValueFilter.Value) _VitalityValuePool.Value.Add(i).value = _baseVitalityValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseVulnerabilityCriticalChanceValueFilter.Value) _VulnerabilityCriticalChanceValuePool.Value.Add(i).value = _baseVulnerabilityCriticalChanceValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseWeaponAttackSpeedValueFilter.Value) _WeaponAttackSpeedValuePool.Value.Add(i).value = _baseWeaponAttackSpeedValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkButton1Filter.Value) _ChargeCostValueActionLinkButton1Pool.Value.Add(i).value = _baseChargeCostValueActionLinkButton1Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkButton2Filter.Value) _ChargeCostValueActionLinkButton2Pool.Value.Add(i).value = _baseChargeCostValueActionLinkButton2Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkButton3Filter.Value) _ChargeCostValueActionLinkButton3Pool.Value.Add(i).value = _baseChargeCostValueActionLinkButton3Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkButton4Filter.Value) _ChargeCostValueActionLinkButton4Pool.Value.Add(i).value = _baseChargeCostValueActionLinkButton4Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkForwardFFilter.Value) _ChargeCostValueActionLinkForwardFPool.Value.Add(i).value = _baseChargeCostValueActionLinkForwardFPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkMouseLeftFilter.Value) _ChargeCostValueActionLinkMouseLeftPool.Value.Add(i).value = _baseChargeCostValueActionLinkMouseLeftPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkMouseRightFilter.Value) _ChargeCostValueActionLinkMouseRightPool.Value.Add(i).value = _baseChargeCostValueActionLinkMouseRightPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkSpaceFilter.Value) _ChargeCostValueActionLinkSpacePool.Value.Add(i).value = _baseChargeCostValueActionLinkSpacePool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueActionLinkSpaceForwardFilter.Value) _ChargeCostValueActionLinkSpaceForwardPool.Value.Add(i).value = _baseChargeCostValueActionLinkSpaceForwardPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeCostValueHealingPotionValueFilter.Value) _ChargeCostValueHealingPotionValuePool.Value.Add(i).value = _baseChargeCostValueHealingPotionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkButton1Filter.Value) _ChargeMaxValueActionLinkButton1Pool.Value.Add(i).value = _baseChargeMaxValueActionLinkButton1Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkButton2Filter.Value) _ChargeMaxValueActionLinkButton2Pool.Value.Add(i).value = _baseChargeMaxValueActionLinkButton2Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkButton3Filter.Value) _ChargeMaxValueActionLinkButton3Pool.Value.Add(i).value = _baseChargeMaxValueActionLinkButton3Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkButton4Filter.Value) _ChargeMaxValueActionLinkButton4Pool.Value.Add(i).value = _baseChargeMaxValueActionLinkButton4Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkForwardFFilter.Value) _ChargeMaxValueActionLinkForwardFPool.Value.Add(i).value = _baseChargeMaxValueActionLinkForwardFPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkMouseLeftFilter.Value) _ChargeMaxValueActionLinkMouseLeftPool.Value.Add(i).value = _baseChargeMaxValueActionLinkMouseLeftPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkMouseRightFilter.Value) _ChargeMaxValueActionLinkMouseRightPool.Value.Add(i).value = _baseChargeMaxValueActionLinkMouseRightPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkSpaceFilter.Value) _ChargeMaxValueActionLinkSpacePool.Value.Add(i).value = _baseChargeMaxValueActionLinkSpacePool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueActionLinkSpaceForwardFilter.Value) _ChargeMaxValueActionLinkSpaceForwardPool.Value.Add(i).value = _baseChargeMaxValueActionLinkSpaceForwardPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeMaxValueHealingPotionValueFilter.Value) _ChargeMaxValueHealingPotionValuePool.Value.Add(i).value = _baseChargeMaxValueHealingPotionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkButton1Filter.Value) _ChargeValueActionLinkButton1Pool.Value.Add(i).value = _baseChargeValueActionLinkButton1Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkButton2Filter.Value) _ChargeValueActionLinkButton2Pool.Value.Add(i).value = _baseChargeValueActionLinkButton2Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkButton3Filter.Value) _ChargeValueActionLinkButton3Pool.Value.Add(i).value = _baseChargeValueActionLinkButton3Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkButton4Filter.Value) _ChargeValueActionLinkButton4Pool.Value.Add(i).value = _baseChargeValueActionLinkButton4Pool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkForwardFFilter.Value) _ChargeValueActionLinkForwardFPool.Value.Add(i).value = _baseChargeValueActionLinkForwardFPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkMouseLeftFilter.Value) _ChargeValueActionLinkMouseLeftPool.Value.Add(i).value = _baseChargeValueActionLinkMouseLeftPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkMouseRightFilter.Value) _ChargeValueActionLinkMouseRightPool.Value.Add(i).value = _baseChargeValueActionLinkMouseRightPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkSpaceFilter.Value) _ChargeValueActionLinkSpacePool.Value.Add(i).value = _baseChargeValueActionLinkSpacePool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueActionLinkSpaceForwardFilter.Value) _ChargeValueActionLinkSpaceForwardPool.Value.Add(i).value = _baseChargeValueActionLinkSpaceForwardPool.Value.Get(i).baseValue;
            foreach (var i in _baseChargeValueHealingPotionValueFilter.Value) _ChargeValueHealingPotionValuePool.Value.Add(i).value = _baseChargeValueHealingPotionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkButton1Filter.Value) _CooldownValueActionLinkButton1Pool.Value.Add(i).value = _baseCooldownValueActionLinkButton1Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkButton2Filter.Value) _CooldownValueActionLinkButton2Pool.Value.Add(i).value = _baseCooldownValueActionLinkButton2Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkButton3Filter.Value) _CooldownValueActionLinkButton3Pool.Value.Add(i).value = _baseCooldownValueActionLinkButton3Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkButton4Filter.Value) _CooldownValueActionLinkButton4Pool.Value.Add(i).value = _baseCooldownValueActionLinkButton4Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkForwardFFilter.Value) _CooldownValueActionLinkForwardFPool.Value.Add(i).value = _baseCooldownValueActionLinkForwardFPool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkMouseLeftFilter.Value) _CooldownValueActionLinkMouseLeftPool.Value.Add(i).value = _baseCooldownValueActionLinkMouseLeftPool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkMouseRightFilter.Value) _CooldownValueActionLinkMouseRightPool.Value.Add(i).value = _baseCooldownValueActionLinkMouseRightPool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkSpaceFilter.Value) _CooldownValueActionLinkSpacePool.Value.Add(i).value = _baseCooldownValueActionLinkSpacePool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueActionLinkSpaceForwardFilter.Value) _CooldownValueActionLinkSpaceForwardPool.Value.Add(i).value = _baseCooldownValueActionLinkSpaceForwardPool.Value.Get(i).baseValue;
            foreach (var i in _baseCooldownValueHealingPotionValueFilter.Value) _CooldownValueHealingPotionValuePool.Value.Add(i).value = _baseCooldownValueHealingPotionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkButton1Filter.Value) _CostValueActionLinkButton1Pool.Value.Add(i).value = _baseCostValueActionLinkButton1Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkButton2Filter.Value) _CostValueActionLinkButton2Pool.Value.Add(i).value = _baseCostValueActionLinkButton2Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkButton3Filter.Value) _CostValueActionLinkButton3Pool.Value.Add(i).value = _baseCostValueActionLinkButton3Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkButton4Filter.Value) _CostValueActionLinkButton4Pool.Value.Add(i).value = _baseCostValueActionLinkButton4Pool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkForwardFFilter.Value) _CostValueActionLinkForwardFPool.Value.Add(i).value = _baseCostValueActionLinkForwardFPool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkMouseLeftFilter.Value) _CostValueActionLinkMouseLeftPool.Value.Add(i).value = _baseCostValueActionLinkMouseLeftPool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkMouseRightFilter.Value) _CostValueActionLinkMouseRightPool.Value.Add(i).value = _baseCostValueActionLinkMouseRightPool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkSpaceFilter.Value) _CostValueActionLinkSpacePool.Value.Add(i).value = _baseCostValueActionLinkSpacePool.Value.Get(i).baseValue;
            foreach (var i in _baseCostValueActionLinkSpaceForwardFilter.Value) _CostValueActionLinkSpaceForwardPool.Value.Add(i).value = _baseCostValueActionLinkSpaceForwardPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkButton1Filter.Value) _ResourceRecoveryPerHitValueActionLinkButton1Pool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkButton1Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkButton2Filter.Value) _ResourceRecoveryPerHitValueActionLinkButton2Pool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkButton2Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkButton3Filter.Value) _ResourceRecoveryPerHitValueActionLinkButton3Pool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkButton3Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkButton4Filter.Value) _ResourceRecoveryPerHitValueActionLinkButton4Pool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkButton4Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkForwardFFilter.Value) _ResourceRecoveryPerHitValueActionLinkForwardFPool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkForwardFPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkMouseLeftFilter.Value) _ResourceRecoveryPerHitValueActionLinkMouseLeftPool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkMouseLeftPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkMouseRightFilter.Value) _ResourceRecoveryPerHitValueActionLinkMouseRightPool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkMouseRightPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkSpaceFilter.Value) _ResourceRecoveryPerHitValueActionLinkSpacePool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkSpacePool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueActionLinkSpaceForwardFilter.Value) _ResourceRecoveryPerHitValueActionLinkSpaceForwardPool.Value.Add(i).value = _baseResourceRecoveryPerHitValueActionLinkSpaceForwardPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerHitValueHealingPotionValueFilter.Value) _ResourceRecoveryPerHitValueHealingPotionValuePool.Value.Add(i).value = _baseResourceRecoveryPerHitValueHealingPotionValuePool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkButton1Filter.Value) _ResourceRecoveryPerUsingValueActionLinkButton1Pool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkButton1Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkButton2Filter.Value) _ResourceRecoveryPerUsingValueActionLinkButton2Pool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkButton2Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkButton3Filter.Value) _ResourceRecoveryPerUsingValueActionLinkButton3Pool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkButton3Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkButton4Filter.Value) _ResourceRecoveryPerUsingValueActionLinkButton4Pool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkButton4Pool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkForwardFFilter.Value) _ResourceRecoveryPerUsingValueActionLinkForwardFPool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkForwardFPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkMouseLeftFilter.Value) _ResourceRecoveryPerUsingValueActionLinkMouseLeftPool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkMouseLeftPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkMouseRightFilter.Value) _ResourceRecoveryPerUsingValueActionLinkMouseRightPool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkMouseRightPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkSpaceFilter.Value) _ResourceRecoveryPerUsingValueActionLinkSpacePool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkSpacePool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueActionLinkSpaceForwardFilter.Value) _ResourceRecoveryPerUsingValueActionLinkSpaceForwardPool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueActionLinkSpaceForwardPool.Value.Get(i).baseValue;
            foreach (var i in _baseResourceRecoveryPerUsingValueHealingPotionValueFilter.Value) _ResourceRecoveryPerUsingValueHealingPotionValuePool.Value.Add(i).value = _baseResourceRecoveryPerUsingValueHealingPotionValuePool.Value.Get(i).baseValue;
        }
    }
}