//Файл генерируется в GenValueScaleSystemsUtility
using System;
using Core.Components;
using Core.Systems;
using Leopotam.EcsLite;

namespace Core.Generated
{
    // @formatter:off
    public static class ValueScaleSystemsUtility
    {
        public static IEcsSystem BuildScaleSystem(ValueEnum valueEnum, Func<int, float> getScale) => valueEnum switch
        {
            ValueEnum.ActionCostPerSecondValue => new ScaleValueSystem<ActionCostPerSecondValueComponent>(getScale),
            ValueEnum.AddScoreOnDeathValue => new ScaleValueSystem<AddScoreOnDeathValueComponent>(getScale),
            ValueEnum.ArmorPercentValue => new ScaleValueSystem<ArmorPercentValueComponent>(getScale),
            ValueEnum.ArmorPropertyValue => new ScaleValueSystem<ArmorPropertyValueComponent>(getScale),
            ValueEnum.ArmorValue => new ScaleValueSystem<ArmorValueComponent>(getScale),
            ValueEnum.AttackSpeedPercentValue => new ScaleValueSystem<AttackSpeedPercentValueComponent>(getScale),
            ValueEnum.AttackSpeedValue => new ScaleValueSystem<AttackSpeedValueComponent>(getScale),
            ValueEnum.BarbDamageBashValue => new ScaleValueSystem<BarbDamageBashValueComponent>(getScale),
            ValueEnum.BarbDamageCleaveValue => new ScaleValueSystem<BarbDamageCleaveValueComponent>(getScale),
            ValueEnum.BarbDamageFrenzyValue => new ScaleValueSystem<BarbDamageFrenzyValueComponent>(getScale),
            ValueEnum.BarbDamageHammerOfTheAncientsValue => new ScaleValueSystem<BarbDamageHammerOfTheAncientsValueComponent>(getScale),
            ValueEnum.BarbDamageOverPowerValue => new ScaleValueSystem<BarbDamageOverPowerValueComponent>(getScale),
            ValueEnum.BarbDamageRendValue => new ScaleValueSystem<BarbDamageRendValueComponent>(getScale),
            ValueEnum.BarbDamageRevengeValue => new ScaleValueSystem<BarbDamageRevengeValueComponent>(getScale),
            ValueEnum.BarbDamageSeismicSlamValue => new ScaleValueSystem<BarbDamageSeismicSlamValueComponent>(getScale),
            ValueEnum.BarbDamageWeaponThrowValue => new ScaleValueSystem<BarbDamageWeaponThrowValueComponent>(getScale),
            ValueEnum.BarbDamageWhirlwindValue => new ScaleValueSystem<BarbDamageWhirlwindValueComponent>(getScale),
            ValueEnum.BarbFrenzyStackValue => new ScaleValueSystem<BarbFrenzyStackValueComponent>(getScale),
            ValueEnum.BlockAmountMaxValue => new ScaleValueSystem<BlockAmountMaxValueComponent>(getScale),
            ValueEnum.BlockAmountMinValue => new ScaleValueSystem<BlockAmountMinValueComponent>(getScale),
            ValueEnum.BlockChanceValue => new ScaleValueSystem<BlockChanceValueComponent>(getScale),
            ValueEnum.ChargeCostValueActionLinkButton1 => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkButton1Component>>(getScale),
            ValueEnum.ChargeCostValueActionLinkButton2 => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkButton2Component>>(getScale),
            ValueEnum.ChargeCostValueActionLinkButton3 => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkButton3Component>>(getScale),
            ValueEnum.ChargeCostValueActionLinkButton4 => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkButton4Component>>(getScale),
            ValueEnum.ChargeCostValueActionLinkMouseLeft => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkMouseLeftComponent>>(getScale),
            ValueEnum.ChargeCostValueActionLinkMouseRight => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkMouseRightComponent>>(getScale),
            ValueEnum.ChargeCostValueActionLinkSpace => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkSpaceComponent>>(getScale),
            ValueEnum.ChargeCostValueActionLinkSpaceForward => new ScaleValueSystem<ChargeCostValueComponent<ActionLinkSpaceForwardComponent>>(getScale),
            ValueEnum.ChargeCostValueHealingPotionValue => new ScaleValueSystem<ChargeCostValueComponent<HealingPotionValueComponent>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkButton1 => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkButton1Component>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkButton2 => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkButton2Component>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkButton3 => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkButton3Component>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkButton4 => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkButton4Component>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkMouseLeft => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkMouseLeftComponent>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkMouseRight => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkMouseRightComponent>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkSpace => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkSpaceComponent>>(getScale),
            ValueEnum.ChargeMaxValueActionLinkSpaceForward => new ScaleValueSystem<ChargeMaxValueComponent<ActionLinkSpaceForwardComponent>>(getScale),
            ValueEnum.ChargeMaxValueHealingPotionValue => new ScaleValueSystem<ChargeMaxValueComponent<HealingPotionValueComponent>>(getScale),
            ValueEnum.ChargeValueActionLinkButton1 => new ScaleValueSystem<ChargeValueComponent<ActionLinkButton1Component>>(getScale),
            ValueEnum.ChargeValueActionLinkButton2 => new ScaleValueSystem<ChargeValueComponent<ActionLinkButton2Component>>(getScale),
            ValueEnum.ChargeValueActionLinkButton3 => new ScaleValueSystem<ChargeValueComponent<ActionLinkButton3Component>>(getScale),
            ValueEnum.ChargeValueActionLinkButton4 => new ScaleValueSystem<ChargeValueComponent<ActionLinkButton4Component>>(getScale),
            ValueEnum.ChargeValueActionLinkMouseLeft => new ScaleValueSystem<ChargeValueComponent<ActionLinkMouseLeftComponent>>(getScale),
            ValueEnum.ChargeValueActionLinkMouseRight => new ScaleValueSystem<ChargeValueComponent<ActionLinkMouseRightComponent>>(getScale),
            ValueEnum.ChargeValueActionLinkSpace => new ScaleValueSystem<ChargeValueComponent<ActionLinkSpaceComponent>>(getScale),
            ValueEnum.ChargeValueActionLinkSpaceForward => new ScaleValueSystem<ChargeValueComponent<ActionLinkSpaceForwardComponent>>(getScale),
            ValueEnum.ChargeValueHealingPotionValue => new ScaleValueSystem<ChargeValueComponent<HealingPotionValueComponent>>(getScale),
            ValueEnum.CooldownValueActionLinkButton1 => new ScaleValueSystem<CooldownValueComponent<ActionLinkButton1Component>>(getScale),
            ValueEnum.CooldownValueActionLinkButton2 => new ScaleValueSystem<CooldownValueComponent<ActionLinkButton2Component>>(getScale),
            ValueEnum.CooldownValueActionLinkButton3 => new ScaleValueSystem<CooldownValueComponent<ActionLinkButton3Component>>(getScale),
            ValueEnum.CooldownValueActionLinkButton4 => new ScaleValueSystem<CooldownValueComponent<ActionLinkButton4Component>>(getScale),
            ValueEnum.CooldownValueActionLinkMouseLeft => new ScaleValueSystem<CooldownValueComponent<ActionLinkMouseLeftComponent>>(getScale),
            ValueEnum.CooldownValueActionLinkMouseRight => new ScaleValueSystem<CooldownValueComponent<ActionLinkMouseRightComponent>>(getScale),
            ValueEnum.CooldownValueActionLinkSpace => new ScaleValueSystem<CooldownValueComponent<ActionLinkSpaceComponent>>(getScale),
            ValueEnum.CooldownValueActionLinkSpaceForward => new ScaleValueSystem<CooldownValueComponent<ActionLinkSpaceForwardComponent>>(getScale),
            ValueEnum.CooldownValueHealingPotionValue => new ScaleValueSystem<CooldownValueComponent<HealingPotionValueComponent>>(getScale),
            ValueEnum.CostValueActionLinkButton1 => new ScaleValueSystem<CostValueComponent<ActionLinkButton1Component>>(getScale),
            ValueEnum.CostValueActionLinkButton2 => new ScaleValueSystem<CostValueComponent<ActionLinkButton2Component>>(getScale),
            ValueEnum.CostValueActionLinkButton3 => new ScaleValueSystem<CostValueComponent<ActionLinkButton3Component>>(getScale),
            ValueEnum.CostValueActionLinkButton4 => new ScaleValueSystem<CostValueComponent<ActionLinkButton4Component>>(getScale),
            ValueEnum.CostValueActionLinkMouseLeft => new ScaleValueSystem<CostValueComponent<ActionLinkMouseLeftComponent>>(getScale),
            ValueEnum.CostValueActionLinkMouseRight => new ScaleValueSystem<CostValueComponent<ActionLinkMouseRightComponent>>(getScale),
            ValueEnum.CostValueActionLinkSpace => new ScaleValueSystem<CostValueComponent<ActionLinkSpaceComponent>>(getScale),
            ValueEnum.CostValueActionLinkSpaceForward => new ScaleValueSystem<CostValueComponent<ActionLinkSpaceForwardComponent>>(getScale),
            ValueEnum.CriticalChanceValue => new ScaleValueSystem<CriticalChanceValueComponent>(getScale),
            ValueEnum.CriticalDamageValue => new ScaleValueSystem<CriticalDamageValueComponent>(getScale),
            ValueEnum.DamageColdValue => new ScaleValueSystem<DamageColdValueComponent>(getScale),
            ValueEnum.DamageFireValue => new ScaleValueSystem<DamageFireValueComponent>(getScale),
            ValueEnum.DamageLightningValue => new ScaleValueSystem<DamageLightningValueComponent>(getScale),
            ValueEnum.DamageMaxValue => new ScaleValueSystem<DamageMaxValueComponent>(getScale),
            ValueEnum.DamageMinValue => new ScaleValueSystem<DamageMinValueComponent>(getScale),
            ValueEnum.DamagePercentValue => new ScaleValueSystem<DamagePercentValueComponent>(getScale),
            ValueEnum.DamagePhysicalValue => new ScaleValueSystem<DamagePhysicalValueComponent>(getScale),
            ValueEnum.DamagePropertyMaxValue => new ScaleValueSystem<DamagePropertyMaxValueComponent>(getScale),
            ValueEnum.DamagePropertyMinValue => new ScaleValueSystem<DamagePropertyMinValueComponent>(getScale),
            ValueEnum.DamageReflectionPercentValue => new ScaleValueSystem<DamageReflectionPercentValueComponent>(getScale),
            ValueEnum.DamageValue => new ScaleValueSystem<DamageValueComponent>(getScale),
            ValueEnum.DexterityValue => new ScaleValueSystem<DexterityValueComponent>(getScale),
            ValueEnum.EnergyMaxValue => new ScaleValueSystem<EnergyMaxValueComponent>(getScale),
            ValueEnum.EnergyValue => new ScaleValueSystem<EnergyValueComponent>(getScale),
            ValueEnum.EvasionValue => new ScaleValueSystem<EvasionValueComponent>(getScale),
            ValueEnum.ExperienceValue => new ScaleValueSystem<ExperienceValueComponent>(getScale),
            ValueEnum.ExplosionScaleValue => new ScaleValueSystem<ExplosionScaleValueComponent>(getScale),
            ValueEnum.ExtraGoldWhenKillingValue => new ScaleValueSystem<ExtraGoldWhenKillingValueComponent>(getScale),
            ValueEnum.HealingPercentPerSecondValue => new ScaleValueSystem<HealingPercentPerSecondValueComponent>(getScale),
            ValueEnum.HealingPerHitValue => new ScaleValueSystem<HealingPerHitValueComponent>(getScale),
            ValueEnum.HealingPerSecondValue => new ScaleValueSystem<HealingPerSecondValueComponent>(getScale),
            ValueEnum.HealingPotionValue => new ScaleValueSystem<HealingPotionValueComponent>(getScale),
            ValueEnum.HitPointMaxValue => new ScaleValueSystem<HitPointMaxValueComponent>(getScale),
            ValueEnum.HitPointPercentValue => new ScaleValueSystem<HitPointPercentValueComponent>(getScale),
            ValueEnum.HitPointValue => new ScaleValueSystem<HitPointValueComponent>(getScale),
            ValueEnum.IncomingDamagePercentValue => new ScaleValueSystem<IncomingDamagePercentValueComponent>(getScale),
            ValueEnum.IntelligenceValue => new ScaleValueSystem<IntelligenceValueComponent>(getScale),
            ValueEnum.LevelValue => new ScaleValueSystem<LevelValueComponent>(getScale),
            ValueEnum.ManaPointMaxValue => new ScaleValueSystem<ManaPointMaxValueComponent>(getScale),
            ValueEnum.ManaPointRecoveryValue => new ScaleValueSystem<ManaPointRecoveryValueComponent>(getScale),
            ValueEnum.ManaPointValue => new ScaleValueSystem<ManaPointValueComponent>(getScale),
            ValueEnum.MoveSpeedPercentValue => new ScaleValueSystem<MoveSpeedPercentValueComponent>(getScale),
            ValueEnum.MoveSpeedValue => new ScaleValueSystem<MoveSpeedValueComponent>(getScale),
            ValueEnum.RecoveryTimeReductionValue => new ScaleValueSystem<RecoveryTimeReductionValueComponent>(getScale),
            ValueEnum.ResistanceAllValue => new ScaleValueSystem<ResistanceAllValueComponent>(getScale),
            ValueEnum.ResourceCostsReductionValue => new ScaleValueSystem<ResourceCostsReductionValueComponent>(getScale),
            ValueEnum.ResourceRecoveryPerDamageTakenValue => new ScaleValueSystem<ResourceRecoveryPerDamageTakenValueComponent>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkButton1 => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkButton1Component>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkButton2 => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkButton2Component>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkButton3 => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkButton3Component>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkButton4 => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkButton4Component>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkMouseLeft => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkMouseLeftComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkMouseRight => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkMouseRightComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkSpace => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueActionLinkSpaceForward => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<ActionLinkSpaceForwardComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerHitValueHealingPotionValue => new ScaleValueSystem<ResourceRecoveryPerHitValueComponent<HealingPotionValueComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkButton1 => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkButton1Component>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkButton2 => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkButton2Component>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkButton3 => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkButton3Component>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkButton4 => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkButton4Component>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkMouseLeft => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseLeftComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkMouseRight => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkMouseRightComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkSpace => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueActionLinkSpaceForward => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<ActionLinkSpaceForwardComponent>>(getScale),
            ValueEnum.ResourceRecoveryPerUsingValueHealingPotionValue => new ScaleValueSystem<ResourceRecoveryPerUsingValueComponent<HealingPotionValueComponent>>(getScale),
            ValueEnum.SlowdownAnimationValue => new ScaleValueSystem<SlowdownAnimationValueComponent>(getScale),
            ValueEnum.SlowdownMoveValue => new ScaleValueSystem<SlowdownMoveValueComponent>(getScale),
            ValueEnum.StrengthValue => new ScaleValueSystem<StrengthValueComponent>(getScale),
            ValueEnum.VitalityPercentValue => new ScaleValueSystem<VitalityPercentValueComponent>(getScale),
            ValueEnum.VitalityValue => new ScaleValueSystem<VitalityValueComponent>(getScale),
            ValueEnum.VulnerabilityCriticalChanceValue => new ScaleValueSystem<VulnerabilityCriticalChanceValueComponent>(getScale),
            ValueEnum.WeaponAttackSpeedValue => new ScaleValueSystem<WeaponAttackSpeedValueComponent>(getScale),
            _ => throw new ArgumentOutOfRangeException(nameof(valueEnum), valueEnum, null)
        };
    }
}